// Generated by tools/generate_enum_labels.py from upstream
// BG3Extender/GameDefinitions enumerations. Do not edit.

#include "generated_enums.h"

static const ComponentEnumLabel s_AIBoundType_labels[] = {
    { "Move", 0 },
    { "Hit", 1 },
    { "Stand", 2 },
};
const ComponentEnumDef g_enum_AIBoundType = { "AIBoundType", s_AIBoundType_labels, 3 };

static const ComponentEnumLabel s_AIShapeType_labels[] = {
    { "None", 0 },
    { "Box", 1 },
    { "Cylinder", 2 },
};
const ComponentEnumDef g_enum_AIShapeType = { "AIShapeType", s_AIShapeType_labels, 3 };

static const ComponentEnumLabel s_AbilityId_labels[] = {
    { "None", 0 },
    { "Strength", 1 },
    { "Dexterity", 2 },
    { "Constitution", 3 },
    { "Intelligence", 4 },
    { "Wisdom", 5 },
    { "Charisma", 6 },
    { "Sentinel", 7 },
};
const ComponentEnumDef g_enum_AbilityId = { "AbilityId", s_AbilityId_labels, 8 };

static const ComponentEnumLabel s_ActionDataType_labels[] = {
    { "Unknown", 0 },
    { "OpenClose", 1 },
    { "Destroy", 2 },
    { "Teleport", 3 },
    { "CreateSurface", 4 },
    { "DestroyParameters", 5 },
    { "Equip", 6 },
    { "Consume", 7 },
    { "StoryUse", 8 },
    { "Door", 9 },
    { "CreatePuddle", 10 },
    { "Book", 11 },
    { "UseSpell", 12 },
    { "SpellBook", 13 },
    { "Sit", 14 },
    { "Lie", 15 },
    { "Insert", 16 },
    { "Stand", 17 },
    { "Lockpick", 18 },
    { "StoryUseInInventory", 19 },
    { "DisarmTrap", 20 },
    { "ShowStoryElementUI", 22 },
    { "Combine", 23 },
    { "Ladder", 24 },
    { "PlaySound", 26 },
    { "SpawnCharacter", 27 },
    { "Constrain", 28 },
    { "Recipe", 30 },
    { "Unknown31", 31 },
    { "Throw", 32 },
    { "LearnSpell", 33 },
    { "Unknown34", 34 },
    { "Unknown35", 35 },
};
const ComponentEnumDef g_enum_ActionDataType = { "ActionDataType", s_ActionDataType_labels, 33 };

static const ComponentEnumLabel s_AdvantageBoostType_labels[] = {
    { "None", 0 },
    { "Advantage", 1 },
    { "Disadvantage", 2 },
};
const ComponentEnumDef g_enum_AdvantageBoostType = { "AdvantageBoostType", s_AdvantageBoostType_labels, 3 };

static const ComponentEnumLabel s_AdvantageContext_labels[] = {
    { "AttackRoll", 0 },
    { "AttackTarget", 1 },
    { "SavingThrow", 2 },
    { "AllSavingThrows", 3 },
    { "Ability", 4 },
    { "AllAbilities", 5 },
    { "Skill", 6 },
    { "AllSkills", 7 },
    { "SourceDialogue", 8 },
    { "DeathSavingThrow", 9 },
    { "Concentration", 10 },
};
const ComponentEnumDef g_enum_AdvantageContext = { "AdvantageContext", s_AdvantageContext_labels, 11 };

static const ComponentEnumLabel s_AiActionType_labels[] = {
    { "None", 0 },
    { "Consume", 1 },
    { "Spell", 2 },
    { "Fallback", 4 },
    { "Seek", 5 },
    { "WeaponPickUp", 6 },
    { "UseItem", 7 },
};
const ComponentEnumDef g_enum_AiActionType = { "AiActionType", s_AiActionType_labels, 7 };

static const ComponentEnumLabel s_AnimationInstanceChangeType_labels[] = {
    { "StartUpdate", 0 },
    { "StopUpdate", 1 },
};
const ComponentEnumDef g_enum_AnimationInstanceChangeType = { "AnimationInstanceChangeType", s_AnimationInstanceChangeType_labels, 2 };

static const ComponentEnumLabel s_ApprovalReactionScope_labels[] = {
    { "Global", 0 },
    { "Local", 1 },
    { "Dialog", 2 },
};
const ComponentEnumDef g_enum_ApprovalReactionScope = { "ApprovalReactionScope", s_ApprovalReactionScope_labels, 3 };

static const ComponentEnumLabel s_ArmorSetState_labels[] = {
    { "Normal", 0 },
    { "Vanity", 1 },
};
const ComponentEnumDef g_enum_ArmorSetState = { "ArmorSetState", s_ArmorSetState_labels, 2 };

static const ComponentEnumLabel s_ArmorType_labels[] = {
    { "None", 0 },
    { "Cloth", 1 },
    { "Padded", 2 },
    { "Leather", 3 },
    { "StuddedLeather", 4 },
    { "Hide", 5 },
    { "ChainShirt", 6 },
    { "ScaleMail", 7 },
    { "BreastPlate", 8 },
    { "HalfPlate", 9 },
    { "RingMail", 10 },
    { "ChainMail", 11 },
    { "Splint", 12 },
    { "Plate", 13 },
    { "Sentinel", 14 },
};
const ComponentEnumDef g_enum_ArmorType = { "ArmorType", s_ArmorType_labels, 15 };

static const ComponentEnumLabel s_AttackRoll_labels[] = {
    { "None", 0 },
    { "Strength", 1 },
    { "Dexterity", 2 },
    { "Constitution", 3 },
    { "Intelligence", 4 },
    { "Wisdom", 5 },
    { "Charisma", 6 },
    { "SpellCastingAbility", 7 },
    { "UnarmedAttackAbility", 8 },
    { "WeaponAttackAbility", 9 },
};
const ComponentEnumDef g_enum_AttackRoll = { "AttackRoll", s_AttackRoll_labels, 10 };

static const ComponentEnumLabel s_AudioCodec_labels[] = {
    { "Bank", 0 },
    { "PCM", 1 },
    { "ADPCM", 2 },
    { "XMA", 3 },
    { "Vorbis", 4 },
    { "PCMEX", 7 },
    { "External", 8 },
    { "OpusNX", 17 },
    { "Opus", 19 },
    { "OpusWEM", 20 },
};
const ComponentEnumDef g_enum_AudioCodec = { "AudioCodec", s_AudioCodec_labels, 10 };

static const ComponentEnumLabel s_BodyType_labels[] = {
    { "Male", 0 },
    { "Female", 1 },
};
const ComponentEnumDef g_enum_BodyType = { "BodyType", s_BodyType_labels, 2 };

static const ComponentEnumLabel s_BoostSourceType_labels[] = {
    { "Undefined", 0 },
    { "Item", 1 },
    { "Status", 2 },
    { "Passive", 3 },
    { "Story", 4 },
    { "Console", 5 },
    { "Progression", 6 },
    { "Base", 7 },
    { "CharacterCreation", 8 },
    { "Shapeshift", 9 },
    { "Action", 10 },
};
const ComponentEnumDef g_enum_BoostSourceType = { "BoostSourceType", s_BoostSourceType_labels, 11 };

static const ComponentEnumLabel s_BoostType_labels[] = {
    { "JumpMaxDistanceMultiplier", 12 },
    { "ActionResourceConsumeMultiplier", 14 },
    { "HalveWeaponDamage", 17 },
    { "UnlockSpell", 19 },
    { "SourceAdvantageOnAttack", 20 },
    { "ProficiencyBonus", 21 },
    { "Proficiency", 23 },
    { "Reroll", 46 },
    { "DownedStatus", 47 },
    { "WeaponEnchantment", 49 },
    { "GuaranteedChanceRollOutcome", 50 },
    { "Attribute", 51 },
    { "GameplayLight", 53 },
    { "Savant", 56 },
    { "MinimumRollResult", 57 },
    { "CharacterWeaponDamage", 59 },
    { "ActiveCharacterLight", 64 },
    { "WeaponAttackTypeOverride", 67 },
    { "WeaponAttackRollAbilityOverride", 71 },
    { "SightRangeAdditive", 77 },
    { "SightRangeOverride", 80 },
    { "MovementSpeedLimit", 82 },
    { "UnlockSpellVariant", 84 },
    { "ScaleMultiplier", 87 },
    { "DamageReduction", 89 },
    { "ObjectSizeOverride", 93 },
    { "AiArchetypeOverride", 95 },
    { "MaximizeHealing", 99 },
    { "DamageBonus", 101 },
    { "AdvanceSpells", 104 },
    { "CanWalkThrough", 111 },
    { "MonkWeaponDamageDiceOverride", 113 },
    { "HorizontalFOVOverride", 115 },
    { "CharacterUnarmedDamage", 116 },
    { "ActionResourceReplenishTypeOverride", 118 },
    { "ActionResourcePreventReduction", 120 },
    { "AttackSpellOverride", 121 },
    { "Lock", 122 },
    { "IgnorePointBlankDisadvantage", 124 },
    { "UnlockInterrupt", 129 },
    { "JumpMaxDistanceBonus", 131 },
    { "ConcentrationIgnoreDamage", 134 },
    { "IgnoreLowGroundPenalty", 136 },
};
const ComponentEnumDef g_enum_BoostType = { "BoostType", s_BoostType_labels, 43 };

static const ComponentEnumLabel s_CameraTargetRequestType_labels[] = {
    { "SetPlayerTargets", 0 },
    { "Follow", 1 },
    { "Projectile", 2 },
    { "Spell", 3 },
    { "Status", 4 },
    { "Restore", 5 },
    { "ClearTargets", 6 },
    { "DeathAnimation", 7 },
    { "CombatStarted", 8 },
    { "PlayerTurn", 9 },
    { "CharacterAssign", 10 },
    { "Swarm", 11 },
    { "DebugPos", 12 },
};
const ComponentEnumDef g_enum_CameraTargetRequestType = { "CameraTargetRequestType", s_CameraTargetRequestType_labels, 13 };

static const ComponentEnumLabel s_CauseType_labels[] = {
    { "None", 0 },
    { "SurfaceMove", 1 },
    { "SurfaceCreate", 2 },
    { "SurfaceStatus", 3 },
    { "StatusEnter", 4 },
    { "StatusTick", 5 },
    { "Attack", 6 },
    { "Offhand", 7 },
    { "AURA", 8 },
    { "InventoryItem", 9 },
    { "WorldItemThrow", 10 },
    { "Unknown11", 11 },
};
const ComponentEnumDef g_enum_CauseType = { "CauseType", s_CauseType_labels, 12 };

static const ComponentEnumLabel s_ClientCharacterTaskType_labels[] = {
    { "MoveTo", 0 },
    { "ControllerSelection", 1 },
    { "MoveController", 2 },
    { "MoveInDirection", 3 },
    { "Spell", 4 },
    { "Dialog", 5 },
    { "ItemUseRemotely", 6 },
    { "ItemUse", 7 },
    { "Drop", 8 },
    { "ItemInteractArea", 9 },
    { "ItemMove", 10 },
    { "ItemMoveDummy", 11 },
    { "ItemCombine", 12 },
    { "ItemCombineDummy", 13 },
    { "SheathUnsheath", 14 },
    { "Lockpick", 15 },
    { "DisarmTrap", 16 },
    { "Pickpocket", 17 },
    { "PickUp", 18 },
    { "Listen", 19 },
    { "Loot", 20 },
    { "DefaultTargetAction", 22 },
    { "ClimbTo", 23 },
};
const ComponentEnumDef g_enum_ClientCharacterTaskType = { "ClientCharacterTaskType", s_ClientCharacterTaskType_labels, 23 };

static const ComponentEnumLabel s_ClientGameState_labels[] = {
    { "Unknown", 0 },
    { "LoadLevel", 10 },
    { "Join", 20 },
    { "GeneratePsoCache", 32 },
};
const ComponentEnumDef g_enum_ClientGameState = { "ClientGameState", s_ClientGameState_labels, 4 };

static const ComponentEnumLabel s_CombatPauseSourceType_labels[] = {
    { "Unknown", 0 },
    { "Script", 1 },
};
const ComponentEnumDef g_enum_CombatPauseSourceType = { "CombatPauseSourceType", s_CombatPauseSourceType_labels, 2 };

static const ComponentEnumLabel s_ContainerInteractionType_labels[] = {
    { "Sort", 0 },
    { "Scatter", 1 },
};
const ComponentEnumDef g_enum_ContainerInteractionType = { "ContainerInteractionType", s_ContainerInteractionType_labels, 2 };

static const ComponentEnumLabel s_CursorType_labels[] = {
    { "None", 0 },
    { "System", 1 },
    { "Arrow", 2 },
    { "ArrowWarning", 3 },
    { "Bow", 4 },
    { "BowWarning", 5 },
    { "BowGround", 6 },
    { "Wand", 7 },
    { "WandWarning", 8 },
    { "WandGround", 9 },
    { "Backstab", 10 },
    { "BackstabWarning", 11 },
    { "Cast", 12 },
    { "CastWarning", 13 },
    { "Combine", 14 },
    { "CombineWarning", 15 },
    { "ItemMove", 20 },
    { "ItemMoveWarning", 21 },
    { "ItemUse", 22 },
    { "ItemUseWarning", 23 },
    { "ItemPickup", 24 },
    { "ItemPickupWarning", 25 },
    { "Lock", 26 },
    { "LockWarning", 27 },
    { "Melee", 28 },
    { "MeleeWarning", 29 },
    { "MeleeGround", 30 },
    { "OpenContainer", 31 },
    { "OpenContainerWarning", 32 },
    { "OpenContainerNew", 33 },
    { "OpenDoor", 34 },
    { "OpenDoorWarning", 35 },
    { "PickPocket", 36 },
    { "PickPocketWarning", 37 },
    { "Shovel", 40 },
    { "ShovelWarning", 41 },
    { "Talk", 42 },
    { "TalkWarning", 43 },
    { "Walk", 44 },
    { "WalkWarning", 45 },
    { "CameraRotation", 46 },
    { "Listen", 47 },
    { "ListenWarning", 48 },
    { "InputText", 50 },
    { "LootedContainer", 51 },
};
const ComponentEnumDef g_enum_CursorType = { "CursorType", s_CursorType_labels, 45 };

static const ComponentEnumLabel s_DamageType_labels[] = {
    { "None", 0 },
    { "Slashing", 1 },
    { "Piercing", 2 },
    { "Bludgeoning", 3 },
    { "Acid", 4 },
    { "Thunder", 5 },
    { "Necrotic", 6 },
    { "Fire", 7 },
    { "Lightning", 8 },
    { "Cold", 9 },
    { "Psychic", 10 },
    { "Poison", 11 },
    { "Radiant", 12 },
    { "Force", 13 },
    { "Sentinel", 14 },
};
const ComponentEnumDef g_enum_DamageType = { "DamageType", s_DamageType_labels, 15 };

static const ComponentEnumLabel s_DealDamageWeaponDamageType_labels[] = {
    { "None", 0 },
    { "MainWeaponDamageType", 1 },
    { "OffhandWeaponDamageType", 2 },
    { "MainMeleeWeaponDamageType", 3 },
    { "OffhandMeleeWeaponDamageType", 4 },
    { "MainRangedWeaponDamageType", 5 },
    { "OffhandRangedWeaponDamageType", 6 },
    { "SourceWeaponDamageType", 7 },
    { "ThrownWeaponDamageType", 8 },
};
const ComponentEnumDef g_enum_DealDamageWeaponDamageType = { "DealDamageWeaponDamageType", s_DealDamageWeaponDamageType_labels, 9 };

static const ComponentEnumLabel s_DealDamageWeaponType_labels[] = {
    { "None", 0 },
    { "MainWeapon", 1 },
    { "OffhandWeapon", 2 },
    { "MainMeleeWeapon", 3 },
    { "OffhandMeleeWeapon", 4 },
    { "MainRangedWeapon", 5 },
    { "OffhandRangedWeapon", 6 },
    { "SourceWeapon", 7 },
    { "UnarmedDamage", 8 },
    { "ThrownWeapon", 9 },
    { "ImprovisedWeapon", 10 },
};
const ComponentEnumDef g_enum_DealDamageWeaponType = { "DealDamageWeaponType", s_DealDamageWeaponType_labels, 11 };

static const ComponentEnumLabel s_DiceSizeId_labels[] = {
    { "D4", 0 },
    { "D6", 1 },
    { "D8", 2 },
    { "D10", 3 },
    { "D12", 4 },
    { "D20", 5 },
    { "D100", 6 },
    { "Default", 8 },
};
const ComponentEnumDef g_enum_DiceSizeId = { "DiceSizeId", s_DiceSizeId_labels, 8 };

static const ComponentEnumLabel s_DisplayNameType_labels[] = {
    { "None", 0 },
    { "Unknown", 1 },
    { "Stats", 2 },
    { "Transform", 4 },
    { "CharacterCreation", 5 },
    { "Template", 6 },
    { "Story", 8 },
};
const ComponentEnumDef g_enum_DisplayNameType = { "DisplayNameType", s_DisplayNameType_labels, 7 };

static const ComponentEnumLabel s_DisplayTitleType_labels[] = {
    { "Transform", 0 },
    { "Story", 1 },
    { "Template", 2 },
};
const ComponentEnumDef g_enum_DisplayTitleType = { "DisplayTitleType", s_DisplayTitleType_labels, 3 };

static const ComponentEnumLabel s_DualWieldingRequestType_labels[] = {
    { "OnItemEquipped", 1 },
    { "OnItemEquipped2", 2 },
    { "ActionResourceChanged", 3 },
    { "BoostChanged", 4 },
    { "ToggleDualWielding", 5 },
    { "ToggleOnCharacterControlChanged", 6 },
};
const ComponentEnumDef g_enum_DualWieldingRequestType = { "DualWieldingRequestType", s_DualWieldingRequestType_labels, 6 };

static const ComponentEnumLabel s_DynamicModifierType_labels[] = {
    { "None", 0 },
    { "Consumable", 1 },
    { "ItemSpell", 2 },
    { "Spell", 3 },
    { "ToggledPassive", 4 },
};
const ComponentEnumDef g_enum_DynamicModifierType = { "DynamicModifierType", s_DynamicModifierType_labels, 5 };

static const ComponentEnumLabel s_EEquipmentType_labels[] = {
    { "Weapon", 0 },
    { "Unknown1", 1 },
    { "Shield", 2 },
    { "Armor", 3 },
    { "Sentinel", 4 },
};
const ComponentEnumDef g_enum_EEquipmentType = { "EEquipmentType", s_EEquipmentType_labels, 5 };

static const ComponentEnumLabel s_EffectPropertyType_labels[] = {
    { "Boolean", 0 },
    { "Integer", 1 },
    { "IntegerRange", 2 },
    { "ColorARGBKeyFrame", 3 },
    { "Float", 4 },
    { "FloatRange", 5 },
    { "FloatKeyFrame", 6 },
    { "String", 7 },
    { "Vector3", 8 },
    { "FixedFunction", 9 },
    { "FixedString", 10 },
    { "Base", 11 },
};
const ComponentEnumDef g_enum_EffectPropertyType = { "EffectPropertyType", s_EffectPropertyType_labels, 12 };

static const ComponentEnumLabel s_EquipmentStatsType_labels[] = {
    { "Weapon", 0 },
    { "Armor", 1 },
    { "Shield", 2 },
};
const ComponentEnumDef g_enum_EquipmentStatsType = { "EquipmentStatsType", s_EquipmentStatsType_labels, 3 };

static const ComponentEnumLabel s_ExecuteWeaponFunctorsType_labels[] = {
    { "MainHand", 0 },
    { "OffHand", 1 },
    { "BothHands", 2 },
    { "Undefined", 3 },
};
const ComponentEnumDef g_enum_ExecuteWeaponFunctorsType = { "ExecuteWeaponFunctorsType", s_ExecuteWeaponFunctorsType_labels, 4 };

static const ComponentEnumLabel s_ForceFunctorAggression_labels[] = {
    { "Aggressive", 0 },
    { "Friendly", 1 },
    { "Neutral", 2 },
    { "Undefined", 3 },
};
const ComponentEnumDef g_enum_ForceFunctorAggression = { "ForceFunctorAggression", s_ForceFunctorAggression_labels, 4 };

static const ComponentEnumLabel s_ForceFunctorOrigin_labels[] = {
    { "OriginToEntity", 0 },
    { "OriginToTarget", 1 },
    { "TargetToEntity", 2 },
    { "Undefined", 3 },
};
const ComponentEnumDef g_enum_ForceFunctorOrigin = { "ForceFunctorOrigin", s_ForceFunctorOrigin_labels, 4 };

static const ComponentEnumLabel s_FunctorContextType_labels[] = {
    { "None", 0 },
    { "AttackTarget", 1 },
    { "AttackPosition", 2 },
    { "Move", 3 },
    { "Target", 4 },
    { "NearbyAttacked", 5 },
    { "NearbyAttacking", 6 },
    { "Equip", 7 },
    { "Source", 8 },
    { "Interrupt", 9 },
};
const ComponentEnumDef g_enum_FunctorContextType = { "FunctorContextType", s_FunctorContextType_labels, 10 };

static const ComponentEnumLabel s_GameActionType_labels[] = {
    { "RainAction", 1 },
    { "StormAction", 2 },
    { "WallAction", 4 },
    { "TornadoAction", 6 },
    { "PathAction", 7 },
    { "GameObjectMoveAction", 8 },
    { "StatusDomeAction", 9 },
};
const ComponentEnumDef g_enum_GameActionType = { "GameActionType", s_GameActionType_labels, 7 };

static const ComponentEnumLabel s_Gender_labels[] = {
    { "Male", 0 },
    { "Female", 1 },
};
const ComponentEnumDef g_enum_Gender = { "Gender", s_Gender_labels, 2 };

static const ComponentEnumLabel s_GenomeVariableType_labels[] = {
    { "Const", 0 },
    { "Unknown1", 1 },
    { "Private", 2 },
    { "Public", 3 },
    { "Extern", 4 },
    { "Socket", 5 },
    { "Function", 6 },
};
const ComponentEnumDef g_enum_GenomeVariableType = { "GenomeVariableType", s_GenomeVariableType_labels, 7 };

static const ComponentEnumLabel s_GravityType_labels[] = {
    { "Enabled", 0 },
    { "Disabled", 1 },
    { "DisabledUntilMove", 2 },
};
const ComponentEnumDef g_enum_GravityType = { "GravityType", s_GravityType_labels, 3 };

static const ComponentEnumLabel s_GuiMeasureScaling_labels[] = {
    { "Absolute", 0 },
    { "Scaled", 1 },
};
const ComponentEnumDef g_enum_GuiMeasureScaling = { "GuiMeasureScaling", s_GuiMeasureScaling_labels, 2 };

static const ComponentEnumLabel s_HandednessType_labels[] = {
    { "Any", 0 },
    { "One", 1 },
    { "Two", 2 },
};
const ComponentEnumDef g_enum_HandednessType = { "HandednessType", s_HandednessType_labels, 3 };

static const ComponentEnumLabel s_HealDirection_labels[] = {
    { "Incoming", 0 },
    { "Outgoing", 1 },
};
const ComponentEnumDef g_enum_HealDirection = { "HealDirection", s_HealDirection_labels, 2 };

static const ComponentEnumLabel s_HealEffect_labels[] = {
    { "None", 0 },
    { "ResistDeath", 1 },
    { "Heal", 2 },
    { "Behavior", 3 },
    { "Unknown4", 4 },
    { "Sitting", 5 },
    { "Surface", 6 },
    { "Lifesteal", 7 },
    { "NegativeDamage", 8 },
    { "Unknown9", 9 },
    { "Script", 10 },
    { "HealSharing", 11 },
    { "Necromantic", 12 },
    { "HealSharingReflected", 13 },
};
const ComponentEnumDef g_enum_HealEffect = { "HealEffect", s_HealEffect_labels, 14 };

static const ComponentEnumLabel s_HitType_labels[] = {
    { "Melee", 0 },
    { "Magic", 1 },
    { "Ranged", 2 },
    { "WeaponDamage", 3 },
    { "Surface", 4 },
    { "DoT", 5 },
    { "Reflected", 6 },
};
const ComponentEnumDef g_enum_HitType = { "HitType", s_HitType_labels, 7 };

static const ComponentEnumLabel s_HitWith_labels[] = {
    { "None", 0 },
    { "Weapon", 1 },
    { "Magic", 2 },
    { "Item", 3 },
    { "Projectile", 4 },
    { "Trap", 5 },
    { "Surface", 6 },
    { "Redirection", 7 },
    { "FallDamage", 8 },
    { "CrushByFall", 9 },
    { "Unknown10", 10 },
    { "Unknown11", 11 },
};
const ComponentEnumDef g_enum_HitWith = { "HitWith", s_HitWith_labels, 12 };

static const ComponentEnumLabel s_IdentityType_labels[] = {
    { "Male", 0 },
    { "Female", 1 },
};
const ComponentEnumDef g_enum_IdentityType = { "IdentityType", s_IdentityType_labels, 2 };

static const ComponentEnumLabel s_IngredientTransformType_labels[] = {
    { "None", 0 },
    { "Consume", 1 },
    { "Transform", 2 },
    { "Boost", 3 },
    { "Poison", 4 },
};
const ComponentEnumDef g_enum_IngredientTransformType = { "IngredientTransformType", s_IngredientTransformType_labels, 5 };

static const ComponentEnumLabel s_IngredientType_labels[] = {
    { "None", 0 },
    { "Object", 1 },
    { "Category", 2 },
    { "Property", 3 },
};
const ComponentEnumDef g_enum_IngredientType = { "IngredientType", s_IngredientType_labels, 4 };

static const ComponentEnumLabel s_InputRawType_labels[] = {
    { "enter", 0 },
    { "escape", 1 },
    { "backspace", 2 },
    { "tab", 3 },
    { "capslock", 4 },
    { "space", 5 },
    { "printscreen", 6 },
    { "scrolllock", 7 },
    { "pause", 8 },
    { "insert", 9 },
    { "home", 10 },
    { "pageup", 11 },
    { "del", 12 },
    { "end", 13 },
    { "pagedown", 14 },
    { "comma", 15 },
    { "hyphen", 16 },
    { "dot", 17 },
    { "slash", 18 },
    { "space2", 19 },
    { "equals", 20 },
    { "leftbracket", 21 },
    { "backslash", 22 },
    { "rightbracket", 23 },
    { "backtick", 24 },
    { "apostrophe", 25 },
    { "num_0", 26 },
    { "num_1", 27 },
    { "num_2", 28 },
    { "num_3", 29 },
    { "num_4", 30 },
    { "num_5", 31 },
    { "num_6", 32 },
    { "num_7", 33 },
    { "num_8", 34 },
    { "num_9", 35 },
    { "a", 36 },
    { "b", 37 },
    { "c", 38 },
    { "d", 39 },
    { "e", 40 },
    { "f", 41 },
    { "g", 42 },
    { "h", 43 },
    { "i", 44 },
    { "j", 45 },
    { "k", 46 },
    { "l", 47 },
    { "m", 48 },
    { "n", 49 },
    { "o", 50 },
    { "p", 51 },
    { "q", 52 },
    { "r", 53 },
    { "s", 54 },
    { "t", 55 },
    { "u", 56 },
    { "v", 57 },
    { "w", 58 },
    { "x", 59 },
    { "y", 60 },
    { "z", 61 },
    { "f1", 62 },
    { "f2", 63 },
    { "f3", 64 },
    { "f4", 65 },
    { "f5", 66 },
    { "f6", 67 },
    { "f7", 68 },
    { "f8", 69 },
    { "f9", 70 },
    { "f10", 71 },
    { "f11", 72 },
    { "f12", 73 },
    { "f13", 74 },
    { "f14", 75 },
    { "f15", 76 },
    { "f16", 77 },
    { "f17", 78 },
    { "f18", 79 },
    { "f19", 80 },
    { "f20", 81 },
    { "f21", 82 },
    { "f22", 83 },
    { "f23", 84 },
    { "f24", 85 },
    { "right", 86 },
    { "left", 87 },
    { "down", 88 },
    { "up", 89 },
    { "numlock", 90 },
    { "kp_divide", 91 },
    { "kp_multiply", 92 },
    { "kp_minus", 93 },
    { "kp_plus", 94 },
    { "kp_enter", 95 },
    { "kp_1", 96 },
    { "kp_2", 97 },
    { "kp_3", 98 },
    { "kp_4", 99 },
    { "kp_5", 100 },
    { "kp_6", 101 },
    { "kp_7", 102 },
    { "kp_8", 103 },
    { "kp_9", 104 },
    { "kp_0", 105 },
    { "kp_period", 106 },
    { "lctrl", 107 },
    { "lshift", 108 },
    { "lalt", 109 },
    { "lgui", 110 },
    { "rctrl", 111 },
    { "rshift", 112 },
    { "ralt", 113 },
    { "rgui", 114 },
    { "mode", 115 },
    { "volume_up", 116 },
    { "volume_down", 117 },
    { "audio_next", 118 },
    { "audio_prev", 119 },
    { "audio_stop", 120 },
    { "audio_play", 121 },
    { "audio_mute", 122 },
    { "left2", 123 },
    { "middle", 124 },
    { "right2", 125 },
    { "x1", 126 },
    { "x2", 127 },
    { "motion", 128 },
    { "motion_xneg", 129 },
    { "motion_ypos", 130 },
    { "motion_xpos", 131 },
    { "motion_yneg", 132 },
    { "wheel_xpos", 133 },
    { "wheel_xneg", 134 },
    { "wheel_ypos", 135 },
    { "wheel_yneg", 136 },
    { "leftstick", 137 },
    { "leftstick_x", 138 },
    { "leftstick_y", 139 },
    { "leftstick_xneg", 140 },
    { "leftstick_ypos", 141 },
    { "leftstick_xpos", 142 },
    { "leftstick_yneg", 143 },
    { "rightstick", 144 },
    { "rightstick_x", 145 },
    { "rightstick_xneg", 146 },
    { "rightstick_y", 147 },
    { "rightstick_ypos", 148 },
    { "rightstick_xpos", 149 },
    { "rightstick_yneg", 150 },
    { "lefttrigger", 151 },
    { "righttrigger", 152 },
    { "controller_a", 153 },
    { "controller_b", 154 },
    { "controller_x", 155 },
    { "controller_y", 156 },
    { "back", 157 },
    { "guide", 158 },
    { "start", 159 },
    { "leftstickpress", 160 },
    { "rightstickpress", 161 },
    { "leftshoulder", 162 },
    { "rightshoulder", 163 },
    { "dpad_up", 164 },
    { "dpad_down", 165 },
    { "dpad_left", 166 },
    { "dpad_right", 167 },
    { "touch_tap", 168 },
    { "touch_hold", 169 },
    { "touch_pinch_in", 170 },
    { "touch_pinch_out", 171 },
    { "touch_rotate", 172 },
    { "touch_flick", 173 },
    { "touch_press", 174 },
    { "item1", 175 },
    { "item2", 176 },
    { "item3", 177 },
    { "item4", 178 },
    { "item5", 179 },
    { "item6", 180 },
    { "item7", 181 },
    { "item8", 182 },
    { "item9", 183 },
    { "item10", 184 },
    { "item11", 185 },
};
const ComponentEnumDef g_enum_InputRawType = { "InputRawType", s_InputRawType_labels, 186 };

static const ComponentEnumLabel s_InputState_labels[] = {
    { "Released", 0 },
    { "Pressed", 1 },
};
const ComponentEnumDef g_enum_InputState = { "InputState", s_InputState_labels, 2 };

static const ComponentEnumLabel s_InterruptDecision_labels[] = {
    { "Use", 0 },
    { "Ignore", 1 },
    { "Ask", 2 },
};
const ComponentEnumDef g_enum_InterruptDecision = { "InterruptDecision", s_InterruptDecision_labels, 3 };

static const ComponentEnumLabel s_InterruptRequestSource_labels[] = {
    { "Boost", 0 },
    { "Debug", 1 },
    { "LearnedSpell", 2 },
};
const ComponentEnumDef g_enum_InterruptRequestSource = { "InterruptRequestSource", s_InterruptRequestSource_labels, 3 };

static const ComponentEnumLabel s_InventoryLockChange_labels[] = {
    { "Lock", 0 },
    { "Unlock", 1 },
    { "Toggle", 2 },
};
const ComponentEnumDef g_enum_InventoryLockChange = { "InventoryLockChange", s_InventoryLockChange_labels, 3 };

static const ComponentEnumLabel s_InventoryType_labels[] = {
    { "Main", 0 },
    { "Equipment", 1 },
    { "Trade", 2 },
    { "Reward", 3 },
    { "KeyChainTest", 4 },
    { "PotionBeltTest", 5 },
    { "Other", 6 },
};
const ComponentEnumDef g_enum_InventoryType = { "InventoryType", s_InventoryType_labels, 7 };

static const ComponentEnumLabel s_IsTradableType_labels[] = {
    { "Default", 0 },
    { "Tradable", 1 },
    { "NonTradable", 2 },
};
const ComponentEnumDef g_enum_IsTradableType = { "IsTradableType", s_IsTradableType_labels, 3 };

static const ComponentEnumLabel s_ItemDataRarity_labels[] = {
    { "Common", 0 },
    { "Unique", 1 },
    { "Uncommon", 2 },
    { "Rare", 3 },
    { "Epic", 4 },
    { "Legendary", 5 },
    { "Divine", 6 },
    { "Sentinel", 7 },
};
const ComponentEnumDef g_enum_ItemDataRarity = { "ItemDataRarity", s_ItemDataRarity_labels, 8 };

static const ComponentEnumLabel s_ItemSlot_labels[] = {
    { "Helmet", 0 },
    { "Breast", 1 },
    { "Cloak", 2 },
    { "MeleeMainHand", 3 },
    { "MeleeOffHand", 4 },
    { "RangedMainHand", 5 },
    { "RangedOffHand", 6 },
    { "Ring", 7 },
    { "Underwear", 8 },
    { "Boots", 9 },
    { "Gloves", 10 },
    { "Amulet", 11 },
    { "Ring2", 12 },
    { "Wings", 13 },
    { "Horns", 14 },
    { "Overhead", 15 },
    { "MusicalInstrument", 16 },
    { "VanityBody", 17 },
    { "VanityBoots", 18 },
    { "MainHand", 19 },
    { "OffHand", 20 },
};
const ComponentEnumDef g_enum_ItemSlot = { "ItemSlot", s_ItemSlot_labels, 21 };

static const ComponentEnumLabel s_ItemUseType_labels[] = {
    { "None", 0 },
    { "Unknown1", 1 },
    { "Grenade", 2 },
    { "Arrow", 3 },
    { "Scroll", 4 },
    { "Potion", 5 },
    { "Throwable", 6 },
    { "Consumable", 7 },
};
const ComponentEnumDef g_enum_ItemUseType = { "ItemUseType", s_ItemUseType_labels, 8 };

static const ComponentEnumLabel s_LevelInstanceState_labels[] = {
    { "Uninitialized", 0 },
    { "Load", 1 },
    { "LoadDependencies", 2 },
    { "Instantiate", 3 },
    { "Instantiated", 4 },
};
const ComponentEnumDef g_enum_LevelInstanceState = { "LevelInstanceState", s_LevelInstanceState_labels, 5 };

static const ComponentEnumLabel s_LightChannelValue_labels[] = {
    { "World", 0 },
    { "Cine1", 1 },
    { "Cine2", 2 },
    { "Cine3", 3 },
    { "Cine4", 4 },
    { "CharacterOnly", 5 },
    { "StealthOnly", 6 },
    { "Custom", 7 },
};
const ComponentEnumDef g_enum_LightChannelValue = { "LightChannelValue", s_LightChannelValue_labels, 8 };

static const ComponentEnumLabel s_LightType_labels[] = {
    { "Point", 0 },
    { "Spot", 1 },
    { "Direction", 2 },
};
const ComponentEnumDef g_enum_LightType = { "LightType", s_LightType_labels, 3 };

static const ComponentEnumLabel s_LongRestState_labels[] = {
    { "Created", 0 },
    { "Validation", 1 },
    { "RestTypeRequest", 2 },
    { "ScriptPhaseStart", 3 },
    { "ScriptPhaseRequested", 4 },
    { "ScriptPhasePending", 5 },
    { "ScriptPhaseTimeout", 6 },
    { "ScriptPhaseDenied", 7 },
    { "Cancelled", 8 },
    { "Finished", 9 },
    { "ReadyForDelete", 10 },
};
const ComponentEnumDef g_enum_LongRestState = { "LongRestState", s_LongRestState_labels, 11 };

static const ComponentEnumLabel s_LongRestType_labels[] = {
    { "None", 0 },
    { "Full", 1 },
    { "Exhausted", 2 },
    { "CanceledByOwner", 3 },
    { "CanceledByObserver", 4 },
    { "CantRest", 5 },
};
const ComponentEnumDef g_enum_LongRestType = { "LongRestType", s_LongRestType_labels, 6 };

static const ComponentEnumLabel s_LongRestUserState_labels[] = {
    { "Initial", 0 },
    { "StartingRest", 1 },
    { "RequestingData", 2 },
    { "Resting", 3 },
    { "WaitingConfirmation", 4 },
    { "WaitingOthers", 5 },
    { "Finishing", 6 },
    { "Finished", 7 },
};
const ComponentEnumDef g_enum_LongRestUserState = { "LongRestUserState", s_LongRestUserState_labels, 8 };

static const ComponentEnumLabel s_LuaTypeId_labels[] = {
    { "Unknown", 0 },
    { "Void", 1 },
    { "Boolean", 2 },
    { "Integer", 3 },
    { "Float", 4 },
    { "String", 5 },
    { "Object", 6 },
    { "Array", 7 },
    { "Set", 8 },
    { "Map", 9 },
    { "Tuple", 10 },
    { "Enumeration", 11 },
    { "Function", 12 },
    { "Any", 13 },
    { "Nullable", 14 },
    { "Module", 15 },
    { "Variant", 16 },
};
const ComponentEnumDef g_enum_LuaTypeId = { "LuaTypeId", s_LuaTypeId_labels, 17 };

static const ComponentEnumLabel s_MovementSpeedType_labels[] = {
    { "None", 0 },
    { "Stroll", 1 },
    { "Walk", 2 },
    { "Run", 3 },
    { "Sprint", 4 },
};
const ComponentEnumDef g_enum_MovementSpeedType = { "MovementSpeedType", s_MovementSpeedType_labels, 5 };

static const ComponentEnumLabel s_NarrativeCombatRequestType_labels[] = {
    { "Create", 0 },
    { "Destroy", 1 },
    { "SetInNarrativeCombat", 2 },
    { "ClearInNarrativeCombat", 3 },
};
const ComponentEnumDef g_enum_NarrativeCombatRequestType = { "NarrativeCombatRequestType", s_NarrativeCombatRequestType_labels, 4 };

static const ComponentEnumLabel s_NetMessage_labels[] = {
    { "NETMSG_HANDSHAKE", 1 },
    { "NETMSG_HOST_WELCOME", 2 },
    { "NETMSG_HOST_REFUSE", 3 },
    { "NETMSG_HOST_REFUSEPLAYER", 4 },
    { "NETMSG_CLIENT_JOINED", 8 },
    { "NETMSG_CLIENT_LEFT", 9 },
    { "NETMSG_HOST_LEFT", 5 },
    { "NETMSG_CLIENT_CONNECT", 6 },
    { "NETMSG_CLIENT_ACCEPT", 7 },
    { "NETMSG_PLAYER_CONNECT", 10 },
    { "NETMSG_PLAYER_DISCONNECT", 11 },
    { "NETMSG_PLAYER_JOINED", 13 },
    { "NETMSG_PLAYER_ACCEPT", 12 },
    { "NETMSG_PLAYER_LEFT", 14 },
    { "NETMSG_PLAYER_CHANGENAME", 15 },
    { "NETMSG_PLAYER_NAMECHANGED", 16 },
    { "NETMSG_ECS_REPLICATION", 17 },
    { "NETMSG_VOICEDATA", 18 },
    { "NETMSG_MIC_DISABLED", 20 },
    { "NETMSG_SKIPMOVIE_RESULT", 19 },
    { "NETMSG_CHAT", 185 },
    { "NETMSG_PEER_ACTIVATE", 118 },
    { "NETMSG_PEER_DEACTIVATE", 119 },
    { "NETMSG_MODULE_LOAD", 192 },
    { "NETMSG_MODULE_LOADED", 193 },
    { "NETMSG_SESSION_LOAD", 194 },
    { "NETMSG_SESSION_LOADED", 195 },
    { "NETMSG_SESSION_UNLOADED", 196 },
    { "NETMSG_LEVEL_LOAD", 197 },
    { "NETMSG_LEVEL_CREATED", 198 },
    { "NETMSG_LEVEL_LOADED", 199 },
    { "NETMSG_LOAD_START", 200 },
    { "NETMSG_LOAD_STARTED", 201 },
    { "NETMSG_LEVEL_INSTANTIATE_SWAP", 202 },
    { "NETMSG_LEVEL_SWAP_READY", 203 },
    { "NETMSG_LEVEL_SWAP_COMPLETE", 204 },
    { "NETMSG_LEVEL_START", 205 },
    { "NETMSG_CHARACTER_CREATE", 26 },
    { "NETMSG_CHARACTER_DESTROY", 27 },
    { "NETMSG_CHARACTER_CONFIRMATION", 28 },
    { "NETMSG_CHARACTER_ACTIVATE", 29 },
    { "NETMSG_CHARACTER_DEACTIVATE", 30 },
    { "NETMSG_CHARACTER_ASSIGN", 31 },
    { "NETMSG_CHARACTER_CHANGE_OWNERSHIP", 207 },
    { "NETMSG_CHARACTER_STEERING", 32 },
    { "NETMSG_CHARACTER_MOVEMENT_FALLING", 237 },
    { "NETMSG_CHARACTER_ACTION", 33 },
    { "NETMSG_CHARACTER_ACTION_DATA", 34 },
    { "NETMSG_CHARACTER_ACTION_REQUEST_RESULT", 35 },
    { "NETMSG_CHARACTER_STATUS", 36 },
    { "NETMSG_CHARACTER_STATUS_LIFETIME", 37 },
    { "NETMSG_CHARACTER_DIALOG", 40 },
    { "NETMSG_CHARACTER_USE_MOVEMENT", 43 },
    { "NETMSG_CHARACTER_MOVE_FAILED", 44 },
    { "NETMSG_CHARACTER_SELECTED_CLIMB_ON", 45 },
    { "NETMSG_FOLLOWER_CANT_USE_ITEM", 46 },
    { "NETMSG_CHARACTER_AOO", 47 },
    { "NETMSG_CHARACTER_UPDATE", 38 },
    { "NETMSG_CHARACTER_CONTROL", 39 },
    { "NETMSG_CHARACTER_TRANSFORM", 48 },
    { "NETMSG_CHARACTER_PICKPOCKET", 50 },
    { "NETMSG_CHARACTER_OFFSTAGE", 51 },
    { "NETMSG_CHARACTER_IN_DIALOG", 54 },
    { "NETMSG_CHARACTER_LOOT", 52 },
    { "NETMSG_CHARACTER_ITEM_USED", 53 },
    { "NETMSG_CHARACTER_UNSHEATHING", 41 },
    { "NETMSG_CHARACTER_END_REPOSE", 42 },
    { "NETMSG_CHARACTER_BEHAVIOR", 55 },
    { "NETMSG_PARTYGROUP", 60 },
    { "NETMSG_PARTYORDER", 61 },
    { "NETMSG_PARTY_BLOCKFOLLOW", 64 },
    { "NETMSG_PROJECTILE_CREATE", 92 },
    { "NETMSG_PROJECTILE_UPDATE", 93 },
    { "NETMSG_MULTIPLE_TARGET_OPERATION", 257 },
    { "NETMSG_TURNBASED_FINISHTEAM", 98 },
    { "NETMSG_TURNBASED_SETTEAM", 99 },
    { "NETMSG_TURNBASED_FLEECOMBATRESULT", 100 },
    { "NETMSG_TURNBASED_FLEE_REQUEST", 101 },
    { "NETMSG_TURNBASED_ENDTURN_REQUEST", 102 },
    { "NETMSG_TURNBASED_CANCEL_ENDTURN_REQUEST", 103 },
    { "NETMSG_TURNBASED_BEGIN_CANCEL_ENDTURN_REQUEST", 104 },
    { "NETMSG_TURNBASED_END_CANCEL_ENDTURN_REQUEST", 105 },
    { "NETMSG_TURNBASED_STARTTURN_CONFIRMATION", 106 },
    { "NETMSG_TURNBASED_SKIP_START_DELAY", 107 },
    { "NETMSG_UI_FORCETURNBASED_ENTERED", 108 },
    { "NETMSG_UI_FORCETURNBASED_LEFT", 109 },
    { "NETMSG_UI_FORCETURNBASED_TURN_STARTED", 110 },
    { "NETMSG_UI_FORCETURNBASED_TURN_ENDED", 111 },
    { "NETMSG_ITEM_CREATE", 67 },
    { "NETMSG_ITEM_DESTROY", 68 },
    { "NETMSG_ITEM_ACTIVATE", 69 },
    { "NETMSG_ITEM_DEACTIVATE", 70 },
    { "NETMSG_ITEM_DESTINATION", 71 },
    { "NETMSG_ITEM_UPDATE", 72 },
    { "NETMSG_ITEM_USE_REMOTELY", 73 },
    { "NETMSG_ITEM_MOVE_TO_WORLD", 74 },
    { "NETMSG_ITEM_ACTION", 75 },
    { "NETMSG_ITEM_STATUS", 76 },
    { "NETMSG_ITEM_STATUS_LIFETIME", 77 },
    { "NETMSG_ITEM_TRANSFORM", 78 },
    { "NETMSG_ITEM_CONFIRMATION", 79 },
    { "NETMSG_ITEM_OFFSTAGE", 80 },
    { "NETMSG_ITEM_MOVED_INFORM", 81 },
    { "NETMSG_INVENTORY_CREATE", 82 },
    { "NETMSG_INVENTORY_CREATE_AND_OPEN", 83 },
    { "NETMSG_INVENTORY_DESTROY", 84 },
    { "NETMSG_INVENTORY_VIEW_CREATE", 85 },
    { "NETMSG_INVENTORY_VIEW_DESTROY", 86 },
    { "NETMSG_INVENTORY_VIEW_UPDATE_ITEMS", 87 },
    { "NETMSG_INVENTORY_VIEW_UPDATE_PARENTS", 88 },
    { "NETMSG_INVENTORY_VIEW_SORT", 89 },
    { "NETMSG_INVENTORY_ITEM_UPDATE", 90 },
    { "NETMSG_INVENTORY_LOCKSTATE_SYNC", 91 },
    { "NETMSG_SURFACE_CREATE", 22 },
    { "NETMSG_SURFACE_META", 23 },
    { "NETMSG_DARKNESSTILE_UPDATE", 24 },
    { "NETMSG_GAMEACTION", 25 },
    { "NETMSG_GAMEOVER", 161 },
    { "NETMSG_ACT_OVER", 162 },
    { "NETMSG_SPELL_LEARN", 120 },
    { "NETMSG_SPELL_REMOVE_LEARNED", 121 },
    { "NETMSG_SPELL_PREPARE", 122 },
    { "NETMSG_SPELL_CANCEL", 123 },
    { "NETMSG_TADPOLE_POWER_ADD", 124 },
    { "NETMSG_TADPOLE_POWERS_REMOVE", 125 },
    { "NETMSG_GAMECONTROL_UPDATE_S2C", 129 },
    { "NETMSG_GAMECONTROL_UPDATE_C2S", 130 },
    { "NETMSG_GAMECONTROL_PRICETAG", 131 },
    { "NETMSG_CHANGE_RULESETS", 206 },
    { "NETMSG_REALTIME_MULTIPLAY", 226 },
    { "NETMSG_CHARACTER_ERROR", 133 },
    { "NETMSG_SHOW_ERROR", 254 },
    { "NETMSG_REQUESTAUTOSAVE", 188 },
    { "NETMSG_SAVEGAME", 189 },
    { "NETMSG_SAVEGAMEHANDSHAKE", 190 },
    { "NETMSG_SAVEGAMEHANDSHAKE_SCREENSHOT", 191 },
    { "NETMSG_EFFECT_CREATE", 126 },
    { "NETMSG_EFFECT_FORGET", 127 },
    { "NETMSG_EFFECT_DESTROY", 128 },
    { "NETMSG_CACHETEMPLATE", 134 },
    { "NETMSG_OVERHEADTEXT", 135 },
    { "NETMSG_COMBATLOG", 136 },
    { "NETMSG_COMBATLOGITEMINTERACTION", 137 },
    { "NETMSG_COMBATLOGENTRIES", 138 },
    { "NETMSG_SHOW_ENTER_REGION_UI_MESSAGE", 146 },
    { "NETMSG_CHARACTER_TELEPORT", 49 },
    { "NETMSG_SCREEN_FADE_FINISHED", 139 },
    { "NETMSG_OPEN_CUSTOM_BOOK_UI_MESSAGE", 140 },
    { "NETMSG_CLOSE_CUSTOM_BOOK_UI_MESSAGE", 141 },
    { "NETMSG_OPEN_MESSAGE_BOX_MESSAGE", 142 },
    { "NETMSG_CLOSED_MESSAGE_BOX_MESSAGE", 143 },
    { "NETMSG_OPEN_WAYPOINT_UI_MESSAGE", 144 },
    { "NETMSG_CLOSE_UI_MESSAGE", 145 },
    { "NETMSG_OPEN_CRAFT_UI_MESSAGE", 214 },
    { "NETMSG_JOURNAL_RESET", 147 },
    { "NETMSG_TELEPORT_WAYPOINT", 221 },
    { "NETMSG_QUEST_STEP", 148 },
    { "NETMSG_QUEST_CATEGORY_UPDATE", 149 },
    { "NETMSG_QUEST_PROGRESS", 150 },
    { "NETMSG_QUESTS_LOADED", 151 },
    { "NETMSG_JOURNALRECIPE_UPDATE", 153 },
    { "NETMSG_TROPHY_UPDATE", 152 },
    { "NETMSG_MARKER_UI_UPDATE", 155 },
    { "NETMSG_MARKER_UI_CREATE", 154 },
    { "NETMSG_QUEST_TRACK", 156 },
    { "NETMSG_JOURNALDIALOGLOG_UPDATE", 208 },
    { "NETMSG_UI_QUESTSELECTED", 157 },
    { "NETMSG_MYSTERY_ADVANCED", 158 },
    { "NETMSG_MYSTERY_DISABLED", 159 },
    { "NETMSG_NOTIFICATION", 160 },
    { "NETMSG_REGISTER_WAYPOINT", 163 },
    { "NETMSG_UNLOCK_WAYPOINT", 216 },
    { "NETMSG_LOCK_WAYPOINT", 218 },
    { "NETMSG_FLAG_UPDATE", 164 },
    { "NETMSG_LIGHTING_OVERRIDE", 183 },
    { "NETMSG_ATMOSPHERE_OVERRIDE", 184 },
    { "NETMSG_CAMERA_ACTIVATE", 180 },
    { "NETMSG_CAMERA_ROTATE", 181 },
    { "NETMSG_CAMERA_TARGET", 182 },
    { "NETMSG_SHROUD_UPDATE", 65 },
    { "NETMSG_PLAYMOVIE", 132 },
    { "NETMSG_TRADE_ACTION", 179 },
    { "NETMSG_ACHIEVEMENT_UNLOCKED_MESSAGE", 209 },
    { "NETMSG_SAVEGAME_LOAD_FAIL", 210 },
    { "NETMSG_SERVER_COMMAND", 211 },
    { "NETMSG_SERVER_NOTIFICATION", 212 },
    { "NETMSG_GAMETIME_SYNC", 186 },
    { "NETMSG_STORY_ELEMENT_UI", 213 },
    { "NETMSG_ACHIEVEMENT_PROGRESS_MESSAGE", 215 },
    { "NETMSG_TELEPORT_ACK", 234 },
    { "NETMSG_COMBINE_RESULT", 219 },
    { "NETMSG_UNLOCK_ITEM", 220 },
    { "NETMSG_DIALOG_STATE_MESSAGE", 168 },
    { "NETMSG_DIALOG_NODE_MESSAGE", 169 },
    { "NETMSG_DIALOG_ANSWER_MESSAGE", 170 },
    { "NETMSG_DIALOG_ANSWER_HIGHLIGHT_MESSAGE", 171 },
    { "NETMSG_DIALOG_HISTORY_MESSAGE", 172 },
    { "NETMSG_DIALOG_LISTEN", 227 },
    { "NETMSG_DIALOG_ACTORJOINS_MESSAGE", 173 },
    { "NETMSG_DIALOG_ACTORLEAVES_MESSAGE", 174 },
    { "NETMSG_DIALOG_REPLACESPEAKER_MESSAGE", 175 },
    { "NETMSG_DIALOG_INVALID_ANSWER", 228 },
    { "NETMSG_DIALOG_SUGGESTANSWER_MESSAGE", 176 },
    { "NETMSG_DIALOG_REQUEST_IN_DIALOGUE_ATTACK_MESSAGE", 177 },
    { "NETMSG_DIALOG_TIMELINE_UNLOADED_MESSAGE", 178 },
    { "NETMSG_DIALOG_INSTANCEDIALOGCHANGED", 330 },
    { "NETMSG_LOBBY_DATAUPDATE", 231 },
    { "NETMSG_LOBBY_USERUPDATE", 232 },
    { "NETMSG_LOBBY_STARTGAME", 233 },
    { "NETMSG_CAMERA_SPLINE", 236 },
    { "NETMSG_NET_ENTITY_CREATE", 116 },
    { "NETMSG_NET_ENTITY_DESTROY", 117 },
    { "NETMSG_MUSIC_EVENT", 230 },
    { "NETMSG_MUSIC_STATE", 229 },
    { "NETMSG_PAUSE", 239 },
    { "NETMSG_UNPAUSE", 240 },
    { "NETMSG_READYCHECK", 238 },
    { "NETMSG_DIPLOMACY", 241 },
    { "NETMSG_TRIGGER_CREATE", 242 },
    { "NETMSG_TRIGGER_DESTROY", 243 },
    { "NETMSG_TRIGGER_UPDATE", 244 },
    { "NETMSG_PING_REQUEST", 245 },
    { "NETMSG_CUSTOM_STATS_DEFINITION_CREATE", 246 },
    { "NETMSG_CUSTOM_STATS_DEFINITION_REMOVE", 247 },
    { "NETMSG_CUSTOM_STATS_DEFINITION_UPDATE", 248 },
    { "NETMSG_CUSTOM_STATS_CREATE", 249 },
    { "NETMSG_CUSTOM_STATS_UPDATE", 250 },
    { "NETMSG_GIVE_REWARD", 251 },
    { "NETMSG_LOAD_GAME_WITH_ADDONS", 252 },
    { "NETMSG_LOAD_GAME_WITH_ADDONS_FAIL", 253 },
    { "NETMSG_CLIENT_GAME_SETTINGS", 255 },
    { "NETMSG_DLC_UPDATE", 258 },
    { "NETMSG_TIMELINE_HANDSHAKE", 259 },
    { "NETMSG_TIMELINE_ACTOR_HANDSHAKE", 260 },
    { "NETMSG_TIMELINE_NODECOMPLETED", 261 },
    { "NETMSG_TIMELINE_PLAYER_WATCHING", 262 },
    { "NETMSG_TIMELINE_REQUEST_FASTFORWARD", 263 },
    { "NETMSG_TIMELINE_WORLD_CINEMATIC_COMPLETED", 264 },
    { "NETMSG_CLIENT_DIALOG_PRIVACY_CHANGED", 340 },
    { "NETMSG_CLIENT_DIALOG_JOIN_PRIVACY_FAILED", 341 },
    { "NETMSG_FORCE_TURN_BASED_END_PLAYER_TURN_REQUEST", 265 },
    { "NETMSG_FORCE_TURN_BASED_TOGGLE_REQUEST", 266 },
    { "NETMSG_CHARACTER_REQUEST_WEAPON_SET_SWITCH", 270 },
    { "NETMSG_CHARACTER_REQUEST_ARMOR_SET_SWITCH", 271 },
    { "NETMSG_REQUESTED_ROLL", 267 },
    { "NETMSG_PASSIVE_ROLL_SEQUENCE", 268 },
    { "NETMSG_CHARACTER_PATHING", 269 },
    { "NETMSG_CHARACTER_CREATION_ABORT", 272 },
    { "NETMSG_CHARACTER_CREATION_READY", 273 },
    { "NETMSG_CHARACTER_CREATION_UPDATE", 274 },
    { "NETMSG_CHARACTER_CREATION_PLAYORIGINTIMELINE", 275 },
    { "NETMSG_LEVEL_UP_UPDATE", 276 },
    { "NETMSG_RESPEC_UPDATE", 277 },
    { "NETMSG_FULL_RESPEC_UPDATE", 278 },
    { "NETMSG_CHARACTER_CREATION_LEVELUP", 279 },
    { "NETMSG_CHARACTER_CREATION_RESPEC", 280 },
    { "NETMSG_UI_INTERACTION_STOPPED", 282 },
    { "NETMSG_PASSIVE_TOGGLE", 288 },
    { "NETMSG_DUALWIELDING_TOGGLE", 289 },
    { "NETMSG_UI_COMBINE_OPEN", 281 },
    { "NETMSG_TUTORIAL_CLOSED", 283 },
    { "NETMSG_TUTORIAL_UI_EVENT", 284 },
    { "NETMSG_TUTORIAL_USER_ACTION", 285 },
    { "NETMSG_TUTORIALS_SHOWING", 286 },
    { "NETMSG_TUTORIALS_RESET", 287 },
    { "NETMSG_SNEAKING_CONES_VISIBLE_TOGGLE", 290 },
    { "NETMSG_HOTBAR_SLOT_SET", 291 },
    { "NETMSG_HOTBAR_SLOT_REMOVE_IS_NEW_FLAG", 292 },
    { "NETMSG_HOTBAR_COLUMN_SET", 293 },
    { "NETMSG_HOTBAR_ROWS_SET", 294 },
    { "NETMSG_HOTBAR_ROW_REMOVE", 295 },
    { "NETMSG_HOTBAR_LOCK_SET", 296 },
    { "NETMSG_HOTBAR_CUSTOM_DECK", 297 },
    { "NETMSG_HOTBAR_CURRENT_DECK_SET", 298 },
    { "NETMSG_PARTY_PRESET_SAVE", 299 },
    { "NETMSG_PARTY_PRESET_LOAD", 300 },
    { "NETMSG_PARTY_PRESET_LEVELUP", 301 },
    { "NETMSG_PARTY_PRESET_SPELL", 302 },
    { "NETMSG_STORY_FLAGS_LOAD", 303 },
    { "NETMSG_ACTIVE_ROLL_MODIFIERS", 307 },
    { "NETMSG_CAST_ALL", 223 },
    { "NETMSG_END_THE_DAY", 224 },
    { "NETMSG_ITEM_TOGGLE_IS_WARE", 304 },
    { "NETMSG_LONG_REST_DECISION", 225 },
    { "NETMSG_REQUEST_RELEASE_CONCENTRATION", 306 },
    { "NETMSG_ROLL_STREAM_ROLL_MODE_TYPE", 305 },
    { "NETMSG_SHORT_REST", 222 },
    { "NETMSG_CHARACTER_DROP_ENTITY", 308 },
    { "NETMSG_CHARACTER_CANCEL_DROP_ENTITY", 309 },
    { "NETMSG_CHARACTER_LOCKPICK", 310 },
    { "NETMSG_CHARACTER_TRAPDISARM", 311 },
    { "NETMSG_CHARACTER_IMPROV_WEAPON", 312 },
    { "NETMSG_CHARACTER_STOWED_VISIBILITY", 313 },
    { "NETMSG_DECLUTTERED_ITEMS", 314 },
    { "NETMSG_SPELL_CAST_START_PREVIEW", 315 },
    { "NETMSG_SPELL_CAST_UPDATE_PREVIEW", 316 },
    { "NETMSG_SPELL_CAST_CONFIRM", 317 },
    { "NETMSG_SPELL_CAST_CANCEL", 318 },
    { "NETMSG_SPELL_CAST_CAST", 319 },
    { "NETMSG_USE_ITEM_ACTION", 320 },
    { "NETMSG_INVENTORY_CREATE_NEW", 321 },
    { "NETMSG_INVENTORY_DESTROY_NEW", 322 },
    { "NETMSG_INVENTORY_ADD", 323 },
    { "NETMSG_INVENTORY_MOVETOSLOT", 324 },
    { "NETMSG_INVENTORY_TRANSFER", 325 },
    { "NETMSG_INVENTORY_SORT", 326 },
    { "NETMSG_INVENTORY_EQUIP", 327 },
    { "NETMSG_INVENTORY_UNEQUIP", 328 },
    { "NETMSG_INVENTORY_LOCK", 329 },
    { "NETMSG_CHARACTER_ORIGINAL_TEMPLATE_UPDATE", 331 },
    { "NETMSG_INTERRUPT_DECISION", 332 },
    { "NETMSG_INTERRUPT_SET_ASK_DATA", 333 },
    { "NETMSG_INTERRUPT_SET_ENABLED_DATA", 334 },
    { "NETMSG_SELECT_DICE", 335 },
    { "NETMSG_CAMERA_ARRIVED", 336 },
    { "NETMSG_CLEAR_RECIPE_NEW_FLAG", 337 },
    { "NETMSG_COMBINE_ITEMS", 338 },
    { "NETMSG_NEW_ITEMS_INSIDE", 339 },
    { "NETMSG_SCRIPT_EXTENDER", 400 },
};
const ComponentEnumDef g_enum_NetMessage = { "NetMessage", s_NetMessage_labels, 319 };

static const ComponentEnumLabel s_ObjectSize_labels[] = {
    { "Tiny", 0 },
    { "Small", 1 },
    { "Medium", 2 },
    { "Large", 3 },
    { "Huge", 4 },
    { "Gargantuan", 5 },
    { "Max", 6 },
};
const ComponentEnumDef g_enum_ObjectSize = { "ObjectSize", s_ObjectSize_labels, 7 };

static const ComponentEnumLabel s_ObscuredState_labels[] = {
    { "NoOverride", 0 },
    { "Clear", 1 },
    { "LightlyObscured", 2 },
    { "HeavilyObscured", 3 },
};
const ComponentEnumDef g_enum_ObscuredState = { "ObscuredState", s_ObscuredState_labels, 4 };

static const ComponentEnumLabel s_ObscurityState_labels[] = {
    { "Clear", 0 },
    { "LightlyObscured", 1 },
    { "HeavilyObscured", 2 },
};
const ComponentEnumDef g_enum_ObscurityState = { "ObscurityState", s_ObscurityState_labels, 3 };

static const ComponentEnumLabel s_OsiFunctionType_labels[] = {
    { "Call", 0 },
    { "Query", 1 },
    { "Event", 2 },
    { "DB", 3 },
    { "Proc", 4 },
};
const ComponentEnumDef g_enum_OsiFunctionType = { "OsiFunctionType", s_OsiFunctionType_labels, 5 };

static const ComponentEnumLabel s_OsirisTaskType_labels[] = {
    { "MoveToLocation", 0 },
    { "MoveToObject", 1 },
    { "FleeFromGrid", 2 },
    { "MoveInRange", 3 },
    { "TeleportToLocation", 4 },
    { "Appear", 6 },
    { "Disappear", 7 },
    { "FollowNPC", 8 },
    { "FollowOwnerOrLeader", 9 },
    { "Wander", 10 },
    { "Steer", 11 },
    { "PlayAnimation", 12 },
    { "Drop", 13 },
    { "PickupItem", 14 },
    { "UseItem", 15 },
    { "MoveItem", 16 },
    { "Resurrect", 17 },
    { "UseSpell", 18 },
    { "MoveToAndTalk", 19 },
    { "LookAt", 20 },
    { "Timer", 21 },
    { "AutomatedDialog", 22 },
    { "RateLimitedAutomatedDialog", 23 },
    { "FleeFromRelation", 24 },
    { "FleeFromEntity", 25 },
    { "Combine", 26 },
};
const ComponentEnumDef g_enum_OsirisTaskType = { "OsirisTaskType", s_OsirisTaskType_labels, 26 };

static const ComponentEnumLabel s_PassiveSourceType_labels[] = {
    { "Feat", 0 },
    { "Progression", 1 },
    { "Progression2", 2 },
    { "Status", 3 },
    { "Equipment", 4 },
    { "Stats", 5 },
    { "Tadpole", 6 },
    { "Script", 7 },
    { "Debug", 8 },
};
const ComponentEnumDef g_enum_PassiveSourceType = { "PassiveSourceType", s_PassiveSourceType_labels, 9 };

static const ComponentEnumLabel s_PathRootType_labels[] = {
    { "Root", 0 },
    { "Data", 1 },
    { "Public", 2 },
    { "LocalAppData", 3 },
    { "UserProfile", 4 },
    { "Localization", 5 },
    { "Bin", 6 },
    { "Bin2", 7 },
    { "Mods", 8 },
    { "Projects", 9 },
    { "Public2", 10 },
    { "GameMod", 11 },
    { "EngineMod", 12 },
    { "Scripts", 13 },
    { "WorkingDir", 14 },
    { "Debug", 15 },
    { "Savegame", 16 },
    { "Mods2", 17 },
    { "PhotoMode", 18 },
};
const ComponentEnumDef g_enum_PathRootType = { "PathRootType", s_PathRootType_labels, 19 };

static const ComponentEnumLabel s_PhotoModeAnimationState_labels[] = {
    { "None", 0 },
    { "StaticPose", 1 },
    { "AnimationPlaying", 2 },
    { "AnimationPaused", 3 },
};
const ComponentEnumDef g_enum_PhotoModeAnimationState = { "PhotoModeAnimationState", s_PhotoModeAnimationState_labels, 4 };

static const ComponentEnumLabel s_ProficiencyBonusBoostType_labels[] = {
    { "AttackRoll", 0 },
    { "AttackTarget", 1 },
    { "SavingThrow", 2 },
    { "AllSavingThrows", 3 },
    { "Ability", 4 },
    { "AllAbilities", 5 },
    { "Skill", 6 },
    { "AllSkills", 7 },
    { "SourceDialogue", 8 },
    { "WeaponActionDC", 9 },
};
const ComponentEnumDef g_enum_ProficiencyBonusBoostType = { "ProficiencyBonusBoostType", s_ProficiencyBonusBoostType_labels, 10 };

static const ComponentEnumLabel s_ProgressionSelectorType_labels[] = {
    { "None", 0 },
    { "Race", 1 },
    { "SubRace", 2 },
    { "Class", 3 },
    { "SubClass", 4 },
    { "Feat", 5 },
    { "Passive", 6 },
};
const ComponentEnumDef g_enum_ProgressionSelectorType = { "ProgressionSelectorType", s_ProgressionSelectorType_labels, 7 };

static const ComponentEnumLabel s_ProgressionType_labels[] = {
    { "Class", 0 },
    { "SubClass", 1 },
    { "Race", 2 },
    { "Passive", 3 },
};
const ComponentEnumDef g_enum_ProgressionType = { "ProgressionType", s_ProgressionType_labels, 4 };

static const ComponentEnumLabel s_RenderChannel_labels[] = {
    { "Default", 0 },
    { "Background", 1 },
    { "NearBackground", 2 },
    { "Foreground", 3 },
    { "NearForeground", 4 },
    { "SeparateAlpha", 5 },
};
const ComponentEnumDef g_enum_RenderChannel = { "RenderChannel", s_RenderChannel_labels, 6 };

static const ComponentEnumLabel s_RequirementType_labels[] = {
    { "None", 0 },
    { "Level", 1 },
    { "Strength", 2 },
    { "Dexterity", 3 },
    { "Intelligence", 4 },
    { "Constitution", 5 },
    { "Wisdom", 6 },
    { "PainReflection", 8 },
    { "Ranged", 9 },
    { "Reflexes", 10 },
    { "Vitality", 11 },
    { "Sourcery", 12 },
    { "Telekinesis", 13 },
    { "Necromancy", 15 },
    { "Summoning", 16 },
    { "Sneaking", 17 },
    { "Pickpocket", 18 },
    { "Loremaster", 19 },
    { "Barter", 20 },
    { "Charm", 21 },
    { "Intimidate", 22 },
    { "Reason", 23 },
    { "Persuasion", 24 },
    { "Combat", 25 },
    { "TurnBased", 26 },
    { "Immobile", 27 },
    { "Tag", 28 },
};
const ComponentEnumDef g_enum_RequirementType = { "RequirementType", s_RequirementType_labels, 27 };

static const ComponentEnumLabel s_ResourceBankType_labels[] = {
    { "Visual", 0 },
    { "VisualSet", 1 },
    { "Animation", 2 },
    { "AnimationSet", 3 },
    { "Texture", 4 },
    { "Material", 5 },
    { "Physics", 6 },
    { "Effect", 7 },
    { "Script", 8 },
    { "Sound", 9 },
    { "Lighting", 10 },
    { "Atmosphere", 11 },
    { "AnimationBlueprint", 12 },
    { "MeshProxy", 13 },
    { "MaterialSet", 14 },
    { "BlendSpace", 15 },
    { "FCurve", 16 },
    { "Timeline", 17 },
    { "Dialog", 18 },
    { "VoiceBark", 19 },
    { "TileSet", 20 },
    { "IKRig", 21 },
    { "Skeleton", 22 },
    { "VirtualTexture", 23 },
    { "TerrainBrush", 24 },
    { "ColorList", 25 },
    { "CharacterVisual", 26 },
    { "MaterialPreset", 27 },
    { "SkinPreset", 28 },
    { "ClothCollider", 29 },
    { "DiffusionProfile", 30 },
    { "LightCookie", 31 },
    { "TimelineScene", 32 },
    { "SkeletonMirrorTable", 33 },
    { "Sentinel", 34 },
};
const ComponentEnumDef g_enum_ResourceBankType = { "ResourceBankType", s_ResourceBankType_labels, 35 };

static const ComponentEnumLabel s_RestCancelReason_labels[] = {
    { "None", 0 },
    { "Validation", 1 },
    { "Script", 2 },
    { "RestTypeSelectionCanceled", 3 },
    { "ValidationChangedDuringSelection", 4 },
    { "AnotherPlayerCanceled", 5 },
    { "ForcedCancelOnLoad", 6 },
};
const ComponentEnumDef g_enum_RestCancelReason = { "RestCancelReason", s_RestCancelReason_labels, 7 };

static const ComponentEnumLabel s_RollCritical_labels[] = {
    { "None", 0 },
    { "Success", 1 },
    { "Fail", 2 },
};
const ComponentEnumDef g_enum_RollCritical = { "RollCritical", s_RollCritical_labels, 3 };

static const ComponentEnumLabel s_RollModeType_labels[] = {
    { "Random", 0 },
    { "WeightedRandom", 1 },
    { "Horrible", 2 },
    { "Amazing", 3 },
    { "Average", 4 },
    { "Custom", 5 },
};
const ComponentEnumDef g_enum_RollModeType = { "RollModeType", s_RollModeType_labels, 6 };

static const ComponentEnumLabel s_RollStreamType_labels[] = {
    { "Generic", 0 },
    { "Dialog", 1 },
    { "PlayerSpell", 2 },
    { "NPCSpell", 3 },
    { "PlayerRandomCast", 4 },
    { "NPCRandomCast", 5 },
    { "PlayerDamage", 6 },
    { "NPCDamage", 7 },
};
const ComponentEnumDef g_enum_RollStreamType = { "RollStreamType", s_RollStreamType_labels, 8 };

static const ComponentEnumLabel s_SceneObjectType_labels[] = {
    { "RenderableObject", 0 },
    { "Light", 1 },
    { "LightProbe", 2 },
    { "FogVolume", 3 },
    { "Visual", 4 },
    { "Effect", 5 },
    { "InstanceBatchRenderableObject", 6 },
    { "InstancingObject", 7 },
    { "CullableInstance", 8 },
    { "DeferredDecal", 9 },
    { "RoomTriggerVisual", 10 },
};
const ComponentEnumDef g_enum_SceneObjectType = { "SceneObjectType", s_SceneObjectType_labels, 11 };

static const ComponentEnumLabel s_ServerActionType_labels[] = {
    { "Animation", 2 },
    { "MoveItem", 3 },
    { "KnockedDown", 4 },
    { "UseItem", 5 },
    { "CombineItem", 7 },
    { "TeleportFalling", 8 },
    { "Incapacitated", 9 },
};
const ComponentEnumDef g_enum_ServerActionType = { "ServerActionType", s_ServerActionType_labels, 7 };

static const ComponentEnumLabel s_ServerBehaviourType_labels[] = {
    { "Move", 2 },
    { "Wander", 3 },
    { "Force", 4 },
    { "PickupItem", 5 },
    { "MoveItem", 6 },
    { "MoveAndUseItem", 7 },
    { "Appear", 10 },
    { "MoveToAndTalk", 11 },
    { "FollowCharacter", 12 },
    { "Patrol", 13 },
};
const ComponentEnumDef g_enum_ServerBehaviourType = { "ServerBehaviourType", s_ServerBehaviourType_labels, 10 };

static const ComponentEnumLabel s_ServerConcentrationRequestType_labels[] = {
    { "RemoveTarget", 1 },
    { "AddTarget", 2 },
};
const ComponentEnumDef g_enum_ServerConcentrationRequestType = { "ServerConcentrationRequestType", s_ServerConcentrationRequestType_labels, 2 };

static const ComponentEnumLabel s_ServerDestroyStatusRequestType_labels[] = {
    { "StatusType", 0 },
    { "StatusID", 1 },
    { "StatusEntity", 3 },
    { "StatusHandle", 4 },
    { "SourceEquippedItem", 5 },
    { "RestingEntityInventory", 6 },
    { "Death", 7 },
    { "Cause", 8 },
    { "DifficultyStatus", 9 },
};
const ComponentEnumDef g_enum_ServerDestroyStatusRequestType = { "ServerDestroyStatusRequestType", s_ServerDestroyStatusRequestType_labels, 9 };

static const ComponentEnumLabel s_ServerGameState_labels[] = {
    { "Unknown", 0 },
    { "UnloadSession", 10 },
};
const ComponentEnumDef g_enum_ServerGameState = { "ServerGameState", s_ServerGameState_labels, 2 };

static const ComponentEnumLabel s_ServerMovementType_labels[] = {
    { "MoveTo", 2 },
    { "MoveToSync", 3 },
    { "Idle", 4 },
    { "Climbing", 5 },
    { "Falling", 6 },
    { "Repose", 7 },
};
const ComponentEnumDef g_enum_ServerMovementType = { "ServerMovementType", s_ServerMovementType_labels, 6 };

static const ComponentEnumLabel s_ServerSpellCastSystemEventType_labels[] = {
    { "Finish", 0 },
    { "FinishRemove", 1 },
    { "PreparationStart", 2 },
    { "PreparationEnd", 3 },
    { "LogicExecutionStart", 4 },
    { "LogicExecutionStartRemove", 5 },
    { "LogicExecutionEnd", 6 },
    { "MoveDuringCastInitialize", 7 },
    { "MoveDuringCastStart", 8 },
    { "MoveDuringCastUpdate", 9 },
    { "MoveDuringCastEnd", 10 },
    { "TargetHit", 11 },
    { "TargetHitRemove", 12 },
    { "TargetHitInterruptRemove", 13 },
    { "Cast", 14 },
    { "CastRemove", 15 },
    { "CastHit", 16 },
    { "CastHitRemove", 17 },
    { "CastTextKey", 18 },
    { "CastTextKeyRemove", 19 },
    { "CastTextKeyIndexIncrease", 20 },
    { "WeaponSetRequest", 21 },
    { "IsCastingRemove", 22 },
    { "DestroySpellCastEntity", 23 },
    { "DestroyEventRemove", 24 },
    { "JumpStart", 25 },
    { "PlayAnimation", 26 },
    { "MovementEnd", 27 },
    { "TargetReactionRemove", 28 },
    { "TargetsChanged", 29 },
    { "AddProjectileCache", 30 },
    { "AddZoneRange", 31 },
    { "AddSharedMovement", 32 },
    { "AddServerMovement", 33 },
    { "AddMovementInfo", 34 },
    { "PreviewEnd", 35 },
    { "CounteredSpellCast", 36 },
    { "SpellRollAbort", 37 },
    { "PrecalculationEnd", 38 },
    { "PrecalculatedConditionals", 39 },
    { "ThrowPickupPositionChanged", 40 },
    { "PhaseChange", 41 },
    { "CacheFlagChange", 42 },
    { "UseCostsChange", 43 },
    { "InitializeRolls", 44 },
    { "AdvanceRoll", 45 },
    { "AdvanceReaction", 46 },
    { "FireProjectile", 47 },
    { "ChangeProjectileDelayTimer", 48 },
    { "PopDelayedProjectile", 49 },
    { "InitializeIntermediateTargets", 50 },
    { "ChangeCastHitDelayTimer", 51 },
    { "AddDelayedCastHit", 52 },
    { "PopDelayedCastHit", 53 },
    { "ChangeCastPosition", 54 },
    { "ChangeCastEndPosition", 55 },
    { "ChangeMovementTransactionID", 56 },
    { "CreateZone", 57 },
    { "DoTeleport", 58 },
    { "CreateWall", 59 },
    { "CastOptionsChange", 60 },
    { "TargetsChange", 61 },
    { "PathfindRequest", 62 },
    { "PathfindResults", 63 },
    { "PathfindCleanup", 64 },
    { "ChangeStoryActionId", 65 },
    { "InterruptStart", 66 },
    { "InterruptEventChange", 67 },
    { "InterruptApplyResult", 68 },
    { "AdvanceInterruptAnimationIndex", 69 },
    { "InterruptEnd", 70 },
    { "PrecalculatedInterruptors", 71 },
    { "PushPausedAnimationEvents", 72 },
    { "PurgePausedAnimationEvents", 73 },
    { "ZoneRangeUpdate", 74 },
    { "UpdateConditionals", 75 },
    { "UpdateInterruptors", 76 },
    { "LogicExecutionUpdate", 77 },
    { "PreparationStarting", 78 },
};
const ComponentEnumDef g_enum_ServerSpellCastSystemEventType = { "ServerSpellCastSystemEventType", s_ServerSpellCastSystemEventType_labels, 79 };

static const ComponentEnumLabel s_ServerSteeringType_labels[] = {
    { "Steer", 2 },
    { "LookAt", 3 },
    { "SteerTo", 4 },
    { "Repose", 5 },
    { "SteerTunnel", 6 },
};
const ComponentEnumDef g_enum_ServerSteeringType = { "ServerSteeringType", s_ServerSteeringType_labels, 5 };

static const ComponentEnumLabel s_SetStatusDurationType_labels[] = {
    { "SetMinimum", 0 },
    { "ForceSet", 1 },
    { "Add", 2 },
    { "Multiply", 3 },
    { "Unknown", 4 },
};
const ComponentEnumDef g_enum_SetStatusDurationType = { "SetStatusDurationType", s_SetStatusDurationType_labels, 5 };

static const ComponentEnumLabel s_ShapeshiftChangeType_labels[] = {
    { "Add", 0 },
    { "Multiply", 1 },
    { "Override", 2 },
};
const ComponentEnumDef g_enum_ShapeshiftChangeType = { "ShapeshiftChangeType", s_ShapeshiftChangeType_labels, 3 };

static const ComponentEnumLabel s_ShapeshiftSpellSource_labels[] = {
    { "ShapeshiftRule", 0 },
    { "Unknown", 1 },
    { "Template", 2 },
};
const ComponentEnumDef g_enum_ShapeshiftSpellSource = { "ShapeshiftSpellSource", s_ShapeshiftSpellSource_labels, 3 };

static const ComponentEnumLabel s_ShootThroughType_labels[] = {
    { "GargantuanPassesThrough", 0 },
    { "HugePassesThrough", 1 },
    { "LargePassesThrough", 2 },
    { "MediumPassesThrough", 3 },
    { "SmallPassesThrough", 4 },
    { "TinyPassesThrough", 5 },
    { "AllPassesThrough", 6 },
};
const ComponentEnumDef g_enum_ShootThroughType = { "ShootThroughType", s_ShootThroughType_labels, 7 };

static const ComponentEnumLabel s_SkillId_labels[] = {
    { "Deception", 0 },
    { "Intimidation", 1 },
    { "Performance", 2 },
    { "Persuasion", 3 },
    { "Acrobatics", 4 },
    { "SleightOfHand", 5 },
    { "Stealth", 6 },
    { "Arcana", 7 },
    { "History", 8 },
    { "Investigation", 9 },
    { "Nature", 10 },
    { "Religion", 11 },
    { "Athletics", 12 },
    { "AnimalHandling", 13 },
    { "Insight", 14 },
    { "Medicine", 15 },
    { "Perception", 16 },
    { "Survival", 17 },
    { "Invalid", 18 },
    { "Sentinel", 19 },
};
const ComponentEnumDef g_enum_SkillId = { "SkillId", s_SkillId_labels, 20 };

static const ComponentEnumLabel s_SoundEventType_labels[] = {
    { "Sound", 0 },
    { "Music", 1 },
    { "Ambient", 2 },
    { "HUD", 3 },
    { "CineHUD", 4 },
};
const ComponentEnumDef g_enum_SoundEventType = { "SoundEventType", s_SoundEventType_labels, 5 };

static const ComponentEnumLabel s_SourceAdvantageType_labels[] = {
    { "None", 0 },
    { "SourceAdvantageOnAttack", 1 },
    { "SourceAllyAdvantageOnAttack", 2 },
};
const ComponentEnumDef g_enum_SourceAdvantageType = { "SourceAdvantageType", s_SourceAdvantageType_labels, 3 };

static const ComponentEnumLabel s_SpellAnimationCastEvent_labels[] = {
    { "Prepare", 0 },
    { "Cast", 1 },
    { "CastContinue", 2 },
    { "Cancel", 3 },
    { "Finished", 4 },
    { "TargetingInfo", 5 },
};
const ComponentEnumDef g_enum_SpellAnimationCastEvent = { "SpellAnimationCastEvent", s_SpellAnimationCastEvent_labels, 6 };

static const ComponentEnumLabel s_SpellAttackType_labels[] = {
    { "None", 0 },
    { "DirectHit", 1 },
    { "MeleeWeaponAttack", 2 },
    { "RangedWeaponAttack", 3 },
    { "MeleeOffHandWeaponAttack", 4 },
    { "RangedOffHandWeaponAttack", 5 },
    { "MeleeSpellAttack", 6 },
    { "RangedSpellAttack", 7 },
    { "MeleeUnarmedAttack", 8 },
    { "RangedUnarmedAttack", 9 },
};
const ComponentEnumDef g_enum_SpellAttackType = { "SpellAttackType", s_SpellAttackType_labels, 10 };

static const ComponentEnumLabel s_SpellAttackTypeOverride_labels[] = {
    { "Target_MainHandAttack", 0 },
    { "Target_OffhandAttack", 1 },
    { "Projectile_MainHandAttack", 2 },
    { "Projectile_OffhandAttack", 3 },
    { "Target_UnarmedAttack", 4 },
};
const ComponentEnumDef g_enum_SpellAttackTypeOverride = { "SpellAttackTypeOverride", s_SpellAttackTypeOverride_labels, 5 };

static const ComponentEnumLabel s_SpellCastFailReason_labels[] = {
    { "None", 0 },
    { "Canceled", 2 },
    { "InvalidSpell", 3 },
    { "MissingTarget", 4 },
    { "CantCast", 5 },
    { "InvalidTarget", 6 },
    { "CantUseSource", 7 },
    { "CantSpendUseCosts", 8 },
    { "MissingAnimations", 9 },
    { "MissingTargetPosition", 10 },
    { "TooManyTargets", 11 },
    { "TooFewTargets", 12 },
    { "MissingCaster", 13 },
    { "DeadTarget", 14 },
    { "EqualTargets", 15 },
    { "CantFindCastPosition", 16 },
    { "BlockedRequiredMove", 17 },
    { "InvalidCastPosition", 18 },
    { "CantMove", 19 },
    { "MovementFailed", 20 },
    { "ServerTimeout", 21 },
    { "DeadCaster", 22 },
    { "Countered", 23 },
    { "SpellRollFailure", 24 },
    { "UnsheathFailure", 25 },
};
const ComponentEnumDef g_enum_SpellCastFailReason = { "SpellCastFailReason", s_SpellCastFailReason_labels, 25 };

static const ComponentEnumLabel s_SpellCastPhase_labels[] = {
    { "None", 0 },
    { "ValidationStart", 1 },
    { "ValidationFindCastPosition", 2 },
    { "ValidationFindCastEndPosition", 3 },
    { "ValidationPathfind", 4 },
    { "ValidationFinished", 5 },
    { "MovementStart", 6 },
    { "MovementUpdate", 7 },
    { "MovementSteering", 8 },
    { "MovementFinished", 9 },
    { "PrecalculationStart", 10 },
    { "PrecalculationFinished", 11 },
    { "PrepareStart", 12 },
    { "PrepareUpdate", 13 },
    { "PrepareEnd", 14 },
    { "PrepareFinished", 15 },
    { "LogicExecutionStart", 16 },
    { "LogicExecutionUpdate", 17 },
    { "LogicExecutionInterrupted", 18 },
    { "LogicExecutionEnd", 19 },
    { "LogicExecutionFinished", 20 },
    { "Finished", 21 },
};
const ComponentEnumDef g_enum_SpellCastPhase = { "SpellCastPhase", s_SpellCastPhase_labels, 22 };

static const ComponentEnumLabel s_SpellCooldownType_labels[] = {
    { "Default", 0 },
    { "OncePerTurn", 1 },
    { "OncePerCombat", 2 },
    { "UntilRest", 3 },
    { "OncePerTurnNoRealtime", 4 },
    { "UntilShortRest", 5 },
    { "UntilPerRestPerItem", 6 },
    { "OncePerShortRestPerItem", 7 },
};
const ComponentEnumDef g_enum_SpellCooldownType = { "SpellCooldownType", s_SpellCooldownType_labels, 8 };

static const ComponentEnumLabel s_SpellLearningStrategy_labels[] = {
    { "Singular", 0 },
    { "AddChildren", 1 },
    { "MostPowerful", 2 },
};
const ComponentEnumDef g_enum_SpellLearningStrategy = { "SpellLearningStrategy", s_SpellLearningStrategy_labels, 3 };

static const ComponentEnumLabel s_SpellMetaConditionType_labels[] = {
    { "None", 0 },
    { "Roll", 1 },
    { "OriginRoll", 2 },
    { "ThrowableRoll", 3 },
    { "AoE", 4 },
    { "Target", 5 },
    { "ThrowableTarget", 6 },
    { "Forking", 7 },
    { "Cycle", 8 },
    { "Requirements", 9 },
    { "OriginTarget", 10 },
    { "Highlight", 11 },
    { "ProjectileTarget", 12 },
};
const ComponentEnumDef g_enum_SpellMetaConditionType = { "SpellMetaConditionType", s_SpellMetaConditionType_labels, 13 };

static const ComponentEnumLabel s_SpellModificationSource_labels[] = {
    { "Passive", 0 },
    { "MetaMagic", 1 },
    { "Status", 2 },
    { "Boost", 3 },
};
const ComponentEnumDef g_enum_SpellModificationSource = { "SpellModificationSource", s_SpellModificationSource_labels, 4 };

static const ComponentEnumLabel s_SpellModificationValueType_labels[] = {
    { "AdditiveBase", 0 },
    { "AdditiveFinal", 1 },
    { "Multiplicative", 2 },
    { "Override", 3 },
};
const ComponentEnumDef g_enum_SpellModificationValueType = { "SpellModificationValueType", s_SpellModificationValueType_labels, 4 };

static const ComponentEnumLabel s_SpellPrepareType_labels[] = {
    { "AlwaysPrepared", 0 },
    { "RequiresPreparation", 1 },
    { "Unknown", 2 },
};
const ComponentEnumDef g_enum_SpellPrepareType = { "SpellPrepareType", s_SpellPrepareType_labels, 3 };

static const ComponentEnumLabel s_SpellSchoolId_labels[] = {
    { "None", 0 },
    { "Abjuration", 1 },
    { "Conjuration", 2 },
    { "Divination", 3 },
    { "Enchantment", 4 },
    { "Evocation", 5 },
    { "Illusion", 6 },
    { "Necromancy", 7 },
    { "Transmutation", 8 },
};
const ComponentEnumDef g_enum_SpellSchoolId = { "SpellSchoolId", s_SpellSchoolId_labels, 9 };

static const ComponentEnumLabel s_SpellSourceType_labels[] = {
    { "ProgressionClass", 0 },
    { "ProgressionSubClass", 1 },
    { "ProgressionRace", 2 },
    { "Boost", 3 },
    { "Shapeshift", 4 },
    { "SpellSet2", 5 },
    { "Template", 5 },
    { "SpellSet", 6 },
    { "WeaponAttack", 7 },
    { "WeaponSpell", 7 },
    { "UnarmedAttack", 8 },
    { "Guaranteed", 8 },
    { "Osiris", 9 },
    { "Anubis", 10 },
    { "Behavior", 11 },
    { "Debug", 12 },
    { "EquippedItem", 13 },
    { "UseAction", 13 },
    { "GameActionCreateSurface", 14 },
    { "StormAction", 14 },
    { "Functor", 15 },
    { "CreateExplosion", 16 },
    { "Explosion", 16 },
    { "AiTest", 17 },
    { "Learned", 18 },
    { "Boost2", 19 },
    { "Feat", 19 },
    { "Progression", 20 },
    { "BaseStats", 20 },
    { "RandomCast", 21 },
    { "TadpoleTree", 22 },
    { "Sentinel", 23 },
};
const ComponentEnumDef g_enum_SpellSourceType = { "SpellSourceType", s_SpellSourceType_labels, 32 };

static const ComponentEnumLabel s_SpellType_labels[] = {
    { "None", 0 },
    { "Zone", 1 },
    { "MultiStrike", 2 },
    { "Projectile", 3 },
    { "ProjectileStrike", 4 },
    { "Rush", 5 },
    { "Shout", 6 },
    { "Storm", 7 },
    { "Target", 8 },
    { "Teleportation", 9 },
    { "Wall", 10 },
    { "Throw", 11 },
};
const ComponentEnumDef g_enum_SpellType = { "SpellType", s_SpellType_labels, 12 };

static const ComponentEnumLabel s_StatsContextType_labels[] = {
    { "Unspecified", 0 },
    { "Target", 1 },
    { "Owner", 2 },
    { "Cause", 3 },
};
const ComponentEnumDef g_enum_StatsContextType = { "StatsContextType", s_StatsContextType_labels, 4 };

static const ComponentEnumLabel s_StatsDeathType_labels[] = {
    { "None", 0 },
    { "Acid", 1 },
    { "Chasm", 2 },
    { "DoT", 3 },
    { "Electrocution", 4 },
    { "Explode", 5 },
    { "Falling", 6 },
    { "Incinerate", 7 },
    { "KnockedDown", 8 },
    { "Lifetime", 9 },
    { "Necrotic", 10 },
    { "Physical", 11 },
    { "Psychic", 12 },
    { "Radiant", 13 },
    { "CinematicDeath", 14 },
    { "Cold", 15 },
    { "Disintegrate", 16 },
};
const ComponentEnumDef g_enum_StatsDeathType = { "StatsDeathType", s_StatsDeathType_labels, 17 };

static const ComponentEnumLabel s_StatsExpressionParamType_labels[] = {
    { "StatsExpressionType", 0 },
    { "Type1", 1 },
    { "StatsExpressionVariableDataType", 2 },
    { "StatsExpressionVariableDataModifier", 3 },
    { "RollDefinition", 4 },
    { "ResourceRollDefinition", 5 },
    { "StatsContextType", 6 },
    { "Int", 7 },
    { "Bool", 8 },
};
const ComponentEnumDef g_enum_StatsExpressionParamType = { "StatsExpressionParamType", s_StatsExpressionParamType_labels, 9 };

static const ComponentEnumLabel s_StatsExpressionParamType2_labels[] = {
    { "StatsExpressionVariableData", 0 },
    { "Ability", 1 },
    { "Skill", 2 },
    { "StatusGroup", 3 },
    { "STDString", 4 },
};
const ComponentEnumDef g_enum_StatsExpressionParamType2 = { "StatsExpressionParamType2", s_StatsExpressionParamType2_labels, 5 };

static const ComponentEnumLabel s_StatsExpressionType_labels[] = {
    { "Roll", 0 },
    { "Add", 1 },
    { "Subtract", 2 },
    { "Divide", 3 },
    { "Multiply", 4 },
    { "Max", 5 },
    { "ForEach", 6 },
    { "Placeholder", 7 },
    { "ResourceRoll", 8 },
    { "Variable", 9 },
    { "Negate", 10 },
};
const ComponentEnumDef g_enum_StatsExpressionType = { "StatsExpressionType", s_StatsExpressionType_labels, 11 };

static const ComponentEnumLabel s_StatsExpressionVariableData_labels[] = {
    { "SpellCastingAbility", 0 },
    { "ProficiencyBonus", 1 },
    { "Level", 2 },
    { "SpellDC", 3 },
    { "WeaponActionDC", 4 },
    { "UnarmedMeleeAbility", 5 },
    { "CurrentHP", 6 },
    { "MaxHP", 7 },
    { "SpellPowerLevel", 8 },
    { "TadpolePowersCount", 9 },
    { "DamageDone", 10 },
    { "Sentinel", 11 },
};
const ComponentEnumDef g_enum_StatsExpressionVariableData = { "StatsExpressionVariableData", s_StatsExpressionVariableData_labels, 12 };

static const ComponentEnumLabel s_StatsExpressionVariableDataType_labels[] = {
    { "AbilityOverride", 0 },
    { "SavingThrow", 1 },
    { "StatusDuration", 2 },
    { "StatusStacks", 3 },
    { "CharacterData", 4 },
    { "LevelMapValue", 5 },
    { "ClassLevel", 6 },
};
const ComponentEnumDef g_enum_StatsExpressionVariableDataType = { "StatsExpressionVariableDataType", s_StatsExpressionVariableDataType_labels, 7 };

static const ComponentEnumLabel s_StatsFunctorId_labels[] = {
    { "Extender", 127 },
};
const ComponentEnumDef g_enum_StatsFunctorId = { "StatsFunctorId", s_StatsFunctorId_labels, 1 };

static const ComponentEnumLabel s_StatsItemSlot_labels[] = {
    { "Helmet", 0 },
    { "Breast", 1 },
    { "Cloak", 2 },
    { "MeleeMainHand", 3 },
    { "MeleeOffHand", 4 },
    { "RangedMainHand", 5 },
    { "RangedOffHand", 6 },
    { "Ring", 7 },
    { "Underwear", 8 },
    { "Boots", 9 },
    { "Gloves", 10 },
    { "Amulet", 11 },
    { "Ring2", 12 },
    { "Wings", 13 },
    { "Horns", 14 },
    { "Overhead", 15 },
    { "MusicalInstrument", 16 },
    { "VanityBody", 17 },
    { "VanityBoots", 18 },
    { "MainHand", 19 },
    { "OffHand", 20 },
    { "Max", 21 },
    { "Sentinel", 22 },
};
const ComponentEnumDef g_enum_StatsItemSlot = { "StatsItemSlot", s_StatsItemSlot_labels, 23 };

static const ComponentEnumLabel s_StatsObserverType_labels[] = {
    { "None", 0 },
    { "Observer", 1 },
    { "Target", 2 },
    { "Source", 3 },
};
const ComponentEnumDef g_enum_StatsObserverType = { "StatsObserverType", s_StatsObserverType_labels, 4 };

static const ComponentEnumLabel s_StatsRestoreResourceAmountType_labels[] = {
    { "Lua", 0 },
    { "Percentage", 1 },
    { "None", 2 },
};
const ComponentEnumDef g_enum_StatsRestoreResourceAmountType = { "StatsRestoreResourceAmountType", s_StatsRestoreResourceAmountType_labels, 3 };

static const ComponentEnumLabel s_StatsRollAdjustmentType_labels[] = {
    { "All", 0 },
    { "Distribute", 1 },
};
const ComponentEnumDef g_enum_StatsRollAdjustmentType = { "StatsRollAdjustmentType", s_StatsRollAdjustmentType_labels, 2 };

static const ComponentEnumLabel s_StatsRollType_labels[] = {
    { "None", 0 },
    { "Attack", 1 },
    { "MeleeWeaponAttack", 2 },
    { "RangedWeaponAttack", 3 },
    { "MeleeSpellAttack", 4 },
    { "RangedSpellAttack", 5 },
    { "MeleeUnarmedAttack", 6 },
    { "RangedUnarmedAttack", 7 },
    { "SkillCheck", 8 },
    { "SavingThrow", 9 },
    { "RawAbility", 10 },
    { "Damage", 11 },
    { "MeleeOffHandWeaponAttack", 12 },
    { "RangedOffHandWeaponAttack", 13 },
    { "DeathSavingThrow", 14 },
    { "MeleeWeaponDamage", 15 },
    { "RangedWeaponDamage", 16 },
    { "MeleeSpellDamage", 17 },
    { "RangedSpellDamage", 18 },
    { "MeleeUnarmedDamage", 19 },
    { "RangedUnarmedDamage", 20 },
    { "Sentinel", 21 },
};
const ComponentEnumDef g_enum_StatsRollType = { "StatsRollType", s_StatsRollType_labels, 22 };

static const ComponentEnumLabel s_StatsSize_labels[] = {
    { "None", 0 },
    { "Tiny", 1 },
    { "Small", 2 },
    { "Medium", 3 },
    { "Large", 4 },
    { "Huge", 5 },
    { "Gargantuan", 6 },
};
const ComponentEnumDef g_enum_StatsSize = { "StatsSize", s_StatsSize_labels, 7 };

static const ComponentEnumLabel s_StatsSummonLifetimeType_labels[] = {
    { "Permanent", 0 },
    { "UntilLongRest", 1 },
};
const ComponentEnumDef g_enum_StatsSummonLifetimeType = { "StatsSummonLifetimeType", s_StatsSummonLifetimeType_labels, 2 };

static const ComponentEnumLabel s_StatsUnsheathState_labels[] = {
    { "Instrument", 0 },
    { "Melee", 1 },
    { "Ranged", 2 },
    { "Sheathed", 3 },
};
const ComponentEnumDef g_enum_StatsUnsheathState = { "StatsUnsheathState", s_StatsUnsheathState_labels, 4 };

static const ComponentEnumLabel s_StatsZoneShape_labels[] = {
    { "Cone", 0 },
    { "Square", 1 },
};
const ComponentEnumDef g_enum_StatsZoneShape = { "StatsZoneShape", s_StatsZoneShape_labels, 2 };

static const ComponentEnumLabel s_StatusHealType_labels[] = {
    { "None", 0 },
    { "Vitality", 1 },
    { "PhysicalArmor", 2 },
    { "MagicArmor", 3 },
    { "AllArmor", 4 },
    { "All", 5 },
    { "Source", 6 },
};
const ComponentEnumDef g_enum_StatusHealType = { "StatusHealType", s_StatusHealType_labels, 7 };

static const ComponentEnumLabel s_StatusType_labels[] = {
    { "DYING", 1 },
    { "HEAL", 2 },
    { "KNOCKED_DOWN", 3 },
    { "TELEPORT_FALLING", 4 },
    { "BOOST", 5 },
    { "REACTION", 6 },
    { "STORY_FROZEN", 7 },
    { "SNEAKING", 8 },
    { "UNLOCK", 9 },
    { "FEAR", 10 },
    { "SMELLY", 11 },
    { "INVISIBLE", 12 },
    { "ROTATE", 13 },
    { "MATERIAL", 14 },
    { "CLIMBING", 15 },
    { "INCAPACITATED", 16 },
    { "INSURFACE", 17 },
    { "POLYMORPHED", 18 },
    { "EFFECT", 19 },
    { "DEACTIVATED", 20 },
    { "DOWNED", 21 },
};
const ComponentEnumDef g_enum_StatusType = { "StatusType", s_StatusType_labels, 21 };

static const ComponentEnumLabel s_SurfaceActionType_labels[] = {
    { "None", 0 },
    { "CreateSurface", 1 },
    { "CreatePuddle", 2 },
    { "RemoveSurface", 3 },
    { "Zone", 4 },
    { "TransformSurface", 5 },
    { "ChangeSurfaceOnPath", 6 },
    { "RectangleSurface", 7 },
    { "PolygonSurface", 8 },
    { "ForceCreateSurface", 9 },
    { "CapsuleSurface", 10 },
};
const ComponentEnumDef g_enum_SurfaceActionType = { "SurfaceActionType", s_SurfaceActionType_labels, 11 };

static const ComponentEnumLabel s_SurfaceChange_labels[] = {
    { "None", 0 },
    { "Ignite", 1 },
    { "Douse", 2 },
    { "Electrify", 3 },
    { "Deelectrify", 4 },
    { "Freeze", 5 },
    { "Melt", 6 },
    { "Vaporize", 7 },
    { "Condense", 8 },
    { "DestroyWater", 9 },
    { "Clear", 10 },
    { "Daylight", 11 },
    { "TurnHellfire", 12 },
    { "UnturnHellfire", 13 },
};
const ComponentEnumDef g_enum_SurfaceChange = { "SurfaceChange", s_SurfaceChange_labels, 14 };

static const ComponentEnumLabel s_SurfaceLayer_labels[] = {
    { "Ground", 0 },
    { "Cloud", 1 },
    { "None", 2 },
};
const ComponentEnumDef g_enum_SurfaceLayer = { "SurfaceLayer", s_SurfaceLayer_labels, 3 };

static const ComponentEnumLabel s_SurfaceLayer8_labels[] = {
    { "Ground", 0 },
    { "Cloud", 1 },
    { "None", 2 },
};
const ComponentEnumDef g_enum_SurfaceLayer8 = { "SurfaceLayer8", s_SurfaceLayer8_labels, 3 };

static const ComponentEnumLabel s_SurfaceType_labels[] = {
    { "None", 0 },
    { "Water", 1 },
    { "WaterElectrified", 2 },
    { "WaterFrozen", 3 },
    { "Blood", 4 },
    { "BloodElectrified", 5 },
    { "BloodFrozen", 6 },
    { "Poison", 7 },
    { "Oil", 8 },
    { "Lava", 9 },
    { "Grease", 10 },
    { "WyvernPoison", 11 },
    { "Web", 12 },
    { "Deepwater", 13 },
    { "Vines", 14 },
    { "Fire", 15 },
    { "Acid", 16 },
    { "TrialFire", 17 },
    { "BlackPowder", 18 },
    { "ShadowCursedVines", 19 },
    { "AlienOil", 20 },
    { "Mud", 21 },
    { "Alcohol", 22 },
    { "InvisibleWeb", 23 },
    { "BloodSilver", 24 },
    { "Chasm", 25 },
    { "Hellfire", 26 },
    { "CausticBrine", 27 },
    { "BloodExploding", 28 },
    { "Ash", 29 },
    { "SpikeGrowth", 30 },
    { "HolyFire", 31 },
    { "BlackTentacles", 32 },
    { "Overgrowth", 33 },
    { "PurpleWormPoison", 34 },
    { "SerpentVenom", 35 },
    { "InvisibleGithAcid", 36 },
    { "BladeBarrier", 37 },
    { "Sewer", 38 },
    { "WaterCloud", 39 },
    { "WaterCloudElectrified", 40 },
    { "PoisonCloud", 41 },
    { "ExplosionCloud", 42 },
    { "ShockwaveCloud", 43 },
    { "CloudkillCloud", 44 },
    { "MaliceCloud", 45 },
    { "BloodCloud", 46 },
    { "StinkingCloud", 47 },
    { "DarknessCloud", 48 },
    { "FogCloud", 49 },
    { "GithPheromoneGasCloud", 50 },
    { "SporeWhiteCloud", 51 },
    { "SporeGreenCloud", 52 },
    { "SporeBlackCloud", 53 },
    { "DrowPoisonCloud", 54 },
    { "IceCloud", 55 },
    { "PotionHealingCloud", 56 },
    { "PotionHealingGreaterCloud", 57 },
    { "PotionHealingSuperiorCloud", 58 },
    { "PotionHealingSupremeCloud", 59 },
    { "PotionInvisibilityCloud", 60 },
    { "PotionSpeedCloud", 61 },
    { "PotionVitalityCloud", 62 },
    { "PotionAntitoxinCloud", 63 },
    { "PotionResistanceAcidCloud", 64 },
    { "PotionResistanceColdCloud", 65 },
    { "PotionResistanceFireCloud", 66 },
    { "PotionResistanceForceCloud", 67 },
    { "PotionResistanceLightningCloud", 68 },
    { "PotionResistancePoisonCloud", 69 },
    { "SporePinkCloud", 70 },
    { "BlackPowderDetonationCloud", 71 },
    { "VoidCloud", 72 },
    { "CrawlerMucusCloud", 73 },
    { "Cloudkill6Cloud", 74 },
    { "Sentinel", 75 },
};
const ComponentEnumDef g_enum_SurfaceType = { "SurfaceType", s_SurfaceType_labels, 76 };

static const ComponentEnumLabel s_TemplateType_labels[] = {
    { "RootTemplate", 0 },
    { "GlobalTemplate", 1 },
    { "LocalTemplate", 2 },
    { "CacheTemplate", 3 },
    { "LevelTemplate", 4 },
    { "LevelCacheTemplate", 5 },
};
const ComponentEnumDef g_enum_TemplateType = { "TemplateType", s_TemplateType_labels, 6 };

static const ComponentEnumLabel s_TextKeyType_labels[] = {
    { "Sound", 1 },
    { "Effect", 2 },
    { "FootStep", 3 },
    { "Attach", 4 },
    { "WeaponEffect", 6 },
    { "Genome", 7 },
    { "Attack", 8 },
    { "Ragdoll", 9 },
    { "VisualCullFlag", 10 },
    { "FloatData", 11 },
    { "Foley", 12 },
    { "Vocal", 13 },
    { "FootMove", 14 },
    { "React", 15 },
};
const ComponentEnumDef g_enum_TextKeyType = { "TextKeyType", s_TextKeyType_labels, 14 };

static const ComponentEnumLabel s_TextureType_labels[] = {
    { "T1D", 0 },
    { "T2D", 1 },
    { "T3D", 2 },
    { "T1DArray", 3 },
    { "T2DArray", 4 },
    { "T3DArray", 5 },
    { "T2DCube", 6 },
    { "T2DCubeArray", 7 },
    { "T2DRenderTarget", 8 },
};
const ComponentEnumDef g_enum_TextureType = { "TextureType", s_TextureType_labels, 9 };

static const ComponentEnumLabel s_UnequipType_labels[] = {
    { "ToParentInventory", 0 },
    { "ToParentOrCreatedInventory", 1 },
    { "SwapHands", 2 },
};
const ComponentEnumDef g_enum_UnequipType = { "UnequipType", s_UnequipType_labels, 3 };

static const ComponentEnumLabel s_VisualAttachType_labels[] = {
    { "Root", 0 },
    { "Bone", 1 },
    { "Socket", 2 },
};
const ComponentEnumDef g_enum_VisualAttachType = { "VisualAttachType", s_VisualAttachType_labels, 3 };

static const ComponentEnumLabel s_WeaponSetType_labels[] = {
    { "Melee", 0 },
    { "Ranged", 1 },
    { "Unknown", 2 },
};
const ComponentEnumDef g_enum_WeaponSetType = { "WeaponSetType", s_WeaponSetType_labels, 3 };

static const ComponentEnumLabel s_WeaponType_labels[] = {
    { "None", 0 },
    { "Sword", 1 },
    { "Club", 2 },
    { "Axe", 3 },
    { "Staff", 4 },
    { "Bow", 5 },
    { "Crossbow", 6 },
    { "Spear", 7 },
    { "Knife", 8 },
    { "Wand", 9 },
    { "Arrow", 10 },
    { "Rifle", 11 },
    { "Sentinel", 12 },
};
const ComponentEnumDef g_enum_WeaponType = { "WeaponType", s_WeaponType_labels, 13 };

