#!/usr/bin/env python3
"""Generate src/gen/build_identity.{h,c} from a table of supported builds.

One dylib serves every build listed in SUPPORTED_BUILDS. The store is detected
at runtime and its identity looked up, so the store is not fixed at compile
time.

Steam and GOG ship the same CFBundleShortVersionString as different binaries,
so the version cannot identify a build. Store and arm64 LC_UUID can.

Read a binary's UUID with:

    dwarfdump --uuid "<path to the arm64 game binary>"

For GOG that is Contents/MacOS/"Baldur's Gate 3 GOG" -- the game, not the
arch-selector stub beside it under CFBundleExecutable's name.

Usage:
    python3 tools/gen_build_identity.py            # rewrite in place
    python3 tools/gen_build_identity.py --check    # fail if out of date (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# store, CFBundleShortVersionString, arm64 LC_UUID ("" = unrecorded)
SUPPORTED_BUILDS = [
    ("steam", "4.1.1.7398727", "0C51CAED-6D60-3DCD-9299-8519C92631B0"),
    ("gog",   "4.1.1.7398727", "895FBE6B-5EC6-30F5-A80D-4E1F58D3DDAC"),
]

OUT_DIR = Path(__file__).resolve().parent.parent / "src" / "gen"
TOOL = "tools/gen_build_identity.py"


def render() -> dict[Path, str]:
    versions = {v for _, v, _ in SUPPORTED_BUILDS}
    if len(versions) != 1:
        raise SystemExit(
            f"supported builds no longer share one game version: {sorted(versions)}.\n"
            "BG3_KNOWN_VERSION assumes a single version. Add a per-build version\n"
            "field here and in build_identity.c before adding that build."
        )
    version = versions.pop()
    stores = ", ".join(store for store, _, _ in SUPPORTED_BUILDS)

    header = f'''/**
 * build_identity.h - which game builds this dylib's addresses came from.
 *
 * GENERATED by {TOOL} -- do not edit by hand.
 *
 * One dylib serves every build listed here. The store is detected at runtime
 * and its identity looked up, rather than the store being fixed at compile
 * time.
 *
 * Steam and GOG ship the same CFBundleShortVersionString ({version}) as
 * different binaries, with deltas of -0x7880, -0x78b0, -0x8750 and -0x80e0 on
 * different symbols. The version string therefore cannot tell you which build
 * the game is. Store and binary UUID can.
 *
 * All supported builds are the same game version, so the version stays a
 * single constant. The generator asserts that; add a per-build version field
 * the day it stops being true.
 */

#ifndef BG3SE_BUILD_IDENTITY_H
#define BG3SE_BUILD_IDENTITY_H

#include <stdbool.h>

/* CFBundleShortVersionString every supported build reports. */
#define BG3SE_TARGET_VERSION "{version}"

/* Stores this dylib carries addresses for, for logs and messages. */
#define BG3SE_SUPPORTED_STORES "{stores}"

/** True when this dylib has addresses for that store. */
bool build_identity_supports_store(const char *store);

/**
 * arm64 LC_UUID of the binary the addresses came from, or NULL when the store
 * is unsupported. May be "" when unrecorded: the store check still applies and
 * the UUID check is skipped.
 */
const char *build_identity_uuid_for_store(const char *store);


#endif /* BG3SE_BUILD_IDENTITY_H */
'''

    rows = "\n".join(
        f'    {{ "{store}", "{uuid}" }},' for store, _, uuid in SUPPORTED_BUILDS
    )
    source = f'''/**
 * build_identity.c - per-store build identities.
 *
 * GENERATED by {TOOL} -- do not edit by hand.
 */

#include "build_identity.h"

#include <string.h>

typedef struct {{
    const char *store;
    const char *binary_uuid;   /* arm64 LC_UUID, uppercase-hyphenated, or "" */
}} BuildIdentity;

static const BuildIdentity kIdentities[] = {{
{rows}
}};

static const BuildIdentity *find(const char *store) {{
    if (!store) return NULL;
    for (size_t i = 0; i < sizeof(kIdentities) / sizeof(kIdentities[0]); i++) {{
        if (strcmp(kIdentities[i].store, store) == 0) return &kIdentities[i];
    }}
    return NULL;
}}

bool build_identity_supports_store(const char *store) {{
    return find(store) != NULL;
}}

const char *build_identity_uuid_for_store(const char *store) {{
    const BuildIdentity *id = find(store);
    return id ? id->binary_uuid : NULL;
}}

'''
    return {OUT_DIR / "build_identity.h": header,
            OUT_DIR / "build_identity.c": source}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the files are out of date")
    args = parser.parse_args(argv)

    stale = False
    for path, want in render().items():
        have = path.read_text() if path.exists() else None
        if have == want:
            continue
        stale = True
        if args.check:
            print(f"out of date: {path}", file=sys.stderr)
        else:
            path.write_text(want)
            print(f"wrote {path}")

    if args.check and stale:
        print(f"run: python3 {TOOL}", file=sys.stderr)
        return 1
    if args.check:
        print("build_identity is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
