#!/usr/bin/env python3
"""Generate C enum label tables from upstream BG3SE enumeration definitions.

Parses BEGIN_ENUM/BEGIN_ENUM_NS blocks (not bitmasks) from
upstream/BG3Extender/GameDefinitions/{Enumerations,ExternalEnumerations}/*.inl
and emits src/entity/generated_enums.{h,c} with one ComponentEnumDef per enum.

Labels match upstream exactly so component fields read back the same strings
Windows SE mods see. Bitmasks are excluded: upstream exposes those as flag
tables, which is a different surface.

Usage: generate_enum_labels.py <upstream-gamedefs-dir> <output-dir>
"""
import re
import sys
import os

def parse(paths):
    enums = {}  # name -> list[(label, value)]
    begin_re = re.compile(r'^\s*BEGIN_ENUM(?:_NS)?\(([^)]*)\)')
    ev_re = re.compile(r'^\s*EV\(\s*([A-Za-z0-9_]+)\s*,\s*([^)]+)\)')
    end_re = re.compile(r'^\s*END_ENUM(?:_NS)?\(')
    for path in paths:
        cur = None
        for line in open(path):
            m = begin_re.match(line)
            if m:
                args = [a.strip() for a in m.group(1).split(',')]
                # BEGIN_ENUM(Name, type) | BEGIN_ENUM_NS(ns, Name, LuaName, type)
                name = args[2] if len(args) == 4 else args[0]
                cur = enums.setdefault(name, [])
                continue
            if cur is not None:
                m = ev_re.match(line)
                if m:
                    label, val = m.group(1), m.group(2).strip()
                    try:
                        value = int(val, 0)
                    except ValueError:
                        continue  # expression values don't occur in plain enums
                    cur.append((label, value))
                    continue
                if end_re.match(line):
                    cur = None
    return {k: v for k, v in enums.items() if v}

def main():
    updir, outdir = sys.argv[1], sys.argv[2]
    paths = []
    for sub in ("Enumerations", "ExternalEnumerations"):
        d = os.path.join(updir, sub)
        if os.path.isdir(d):
            paths += [os.path.join(d, f) for f in sorted(os.listdir(d))
                      if f.endswith(".inl")]
    enums = parse(paths)

    h = open(os.path.join(outdir, "generated_enums.h"), "w")
    c = open(os.path.join(outdir, "generated_enums.c"), "w")
    for f in (h, c):
        f.write("// Generated by tools/generate_enum_labels.py from upstream\n"
                "// BG3Extender/GameDefinitions enumerations. Do not edit.\n\n")
    h.write("#ifndef BG3SE_GENERATED_ENUMS_H\n#define BG3SE_GENERATED_ENUMS_H\n\n")
    h.write("#include <stdint.h>\n\n")
    h.write("typedef struct { const char *label; uint64_t value; } ComponentEnumLabel;\n")
    h.write("typedef struct ComponentEnumDef {\n"
            "    const char *name;\n"
            "    const ComponentEnumLabel *labels;\n"
            "    int count;\n"
            "} ComponentEnumDef;\n\n")
    c.write('#include "generated_enums.h"\n\n')

    for name in sorted(enums):
        labels = enums[name]
        c.write(f"static const ComponentEnumLabel s_{name}_labels[] = {{\n")
        for label, value in labels:
            c.write(f'    {{ "{label}", {value} }},\n')
        c.write("};\n")
        c.write(f'const ComponentEnumDef g_enum_{name} = {{ "{name}", '
                f"s_{name}_labels, {len(labels)} }};\n\n")
        h.write(f"extern const ComponentEnumDef g_enum_{name};\n")

    h.write("\n#endif // BG3SE_GENERATED_ENUMS_H\n")
    h.close(); c.close()
    total = sum(len(v) for v in enums.values())
    print(f"generated {len(enums)} enums, {total} labels")

if __name__ == "__main__":
    main()
