#!/usr/bin/env python3
"""
Generate src/entity/generated_component_names.h from the upstream BG3SE headers.

Upstream names every component twice: the engine class
("eoc::tadpole_tree::TreeStateComponent") and the name mods use from Lua
("TadpoleTreeState"), declared together by DEFINE_COMPONENT and its variants
in BG3Extender/GameDefinitions/Components/*.h. The Lua name is not derivable
from the class name (544 of 783 differ), so the mapping has to come from the
headers themselves.

Usage:
    python3 tools/generate_component_names.py [--upstream ~/src/BG3SE/upstream]
"""

import argparse
import os
import re
import sys

MACRO_RE = re.compile(
    r'DEFINE_(?:ONEFRAME_|TAG_|PROXY_)*COMPONENT\s*\(\s*(\w+)\s*,\s*"([^"]+)"'
)


def collect(upstream_root):
    defs_root = os.path.join(upstream_root, "BG3Extender", "GameDefinitions")
    names = {}
    for dirpath, _, files in os.walk(defs_root):
        for fn in files:
            if not fn.endswith(".h"):
                continue
            with open(os.path.join(dirpath, fn), encoding="utf-8", errors="replace") as f:
                for lua_name, cls in MACRO_RE.findall(f.read()):
                    prev = names.get(lua_name)
                    if prev and prev != cls:
                        sys.exit(f"conflict: {lua_name} -> {prev} and {cls}")
                    names[lua_name] = cls
    return names


def emit(names, out_path):
    # Sorted by Lua name with strcmp ordering so the C side can bsearch.
    rows = sorted(names.items(), key=lambda kv: kv[0].encode("ascii"))
    lines = [
        "/*",
        " * BG3SE-macOS Upstream Component Names",
        " *",
        " * GENERATED by tools/generate_component_names.py from the upstream",
        " * BG3SE DEFINE_COMPONENT declarations. Do not edit by hand.",
        " *",
        " * Maps the Lua-facing component name (what mods pass to",
        " * Ext.Entity.OnChange, entity:GetComponent, entity.<Name>, ...) to the",
        " * engine class name the registry is keyed on. Sorted by luaName for",
        " * bsearch with strcmp.",
        " */",
        "",
        "#ifndef BG3SE_GENERATED_COMPONENT_NAMES_H",
        "#define BG3SE_GENERATED_COMPONENT_NAMES_H",
        "",
        "typedef struct {",
        "    const char *luaName;",
        "    const char *className;",
        "} UpstreamComponentName;",
        "",
        "static const UpstreamComponentName g_UpstreamComponentNames[] = {",
    ]
    for lua_name, cls in rows:
        lines.append(f'    {{ "{lua_name}", "{cls}" }},')
    lines += [
        "};",
        "",
        "#define UPSTREAM_COMPONENT_NAME_COUNT "
        "(sizeof(g_UpstreamComponentNames) / sizeof(g_UpstreamComponentNames[0]))",
        "",
        "#endif /* BG3SE_GENERATED_COMPONENT_NAMES_H */",
        "",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return len(rows)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", default=os.path.expanduser("~/src/BG3SE/upstream"))
    ap.add_argument(
        "--out",
        default=os.path.join(here, "..", "src", "entity", "generated_component_names.h"),
    )
    args = ap.parse_args()
    names = collect(args.upstream)
    count = emit(names, os.path.normpath(args.out))
    print(f"wrote {count} component names to {os.path.normpath(args.out)}")


if __name__ == "__main__":
    main()
