#!/usr/bin/env python3
"""
Generate src/staticdata/generated_staticdata_registry.c

Pairs the resource type names Windows BG3SE exposes to Lua (from
upstream/BG3Extender/GameDefinitions/GuidResources.h) with the per-type
m_TypeIndex globals in the game binary:

    ls::TypeId<eoc::ClassDescriptions, ls::ImmutableDataHeadmaster>::m_TypeIndex

The index is read from that global at runtime and used as the key into
ls::ImmutableDataHeadmaster's manager HashMap.
"""
import re, subprocess, sys, os

UPSTREAM = os.path.expanduser("~/src/BG3SE/upstream/BG3Extender/GameDefinitions/GuidResources.h")
IMAGE_BASE = 0x100000000

def type_to_engine_class(path):
    """{ resource type name -> EngineClass } from the GuidResource structs."""
    src = open(path).read()
    out = {}
    # Take each struct header and scan forward to the NEXT struct, rather than a
    # fixed window: several of these bodies (ClassDescription, Feat, Race) are
    # far longer than a capped match allows, and silently dropping them leaves
    # exactly the types most mods ask for out of the registry.
    heads = list(re.finditer(
        r'struct\s+(\w+)\s*:\s*public\s+resource::GuidResource\b', src))
    for i, m in enumerate(heads):
        name = m.group(1)
        end = heads[i + 1].start() if i + 1 < len(heads) else len(src)
        e = re.search(r'EngineClass\s*=\s*"([^"]+)"', src[m.end():end])
        if e:
            out[name] = e.group(1)
    return out

def index_symbols(binary):
    """{ engine class -> file offset of its m_TypeIndex } from the binary."""
    raw = subprocess.run(["nm", "-arch", "arm64", binary],
                         capture_output=True, text=True).stdout
    syms = {}
    for line in raw.splitlines():
        parts = line.split(None, 2)
        if len(parts) < 3 or "ImmutableDataHeadmaster" not in parts[2]:
            continue
        mangled = parts[2].strip()
        if not mangled.startswith("__ZN2ls6TypeId") or "m_TypeIndex" not in mangled:
            continue
        if mangled.startswith("__ZGV"):      # guard variable, not the value
            continue
        dem = subprocess.run(["c++filt", mangled],
                             capture_output=True, text=True).stdout.strip()
        m = re.match(r'ls::TypeId<([^,]+), ls::ImmutableDataHeadmaster>::m_TypeIndex', dem)
        if m:
            syms[m.group(1).strip()] = int(parts[0], 16) - IMAGE_BASE
    return syms

def main():
    if len(sys.argv) < 2:
        print("usage: generate_staticdata_registry.py <arm64 binary>", file=sys.stderr)
        return 1
    types = type_to_engine_class(UPSTREAM)
    syms = index_symbols(sys.argv[1])

    rows, missing = [], []
    for name in sorted(types):
        cls = types[name]
        off = syms.get(cls)
        if off is None:
            missing.append((name, cls))
        else:
            rows.append((name, cls, off))

    print("// Generated by tools/generate_staticdata_registry.py — do not edit.")
    print("// Type names from upstream GuidResources.h; index offsets from the game binary.")
    print('#include "staticdata_registry.h"')
    print('#include <stddef.h>\n')
    print("const StaticDataTypeEntry g_staticdata_types[] = {")
    for name, cls, off in rows:
        print('    { "%s", "%s", 0x%08xULL },' % (name, cls, off))
    print("    { NULL, NULL, 0 }")
    print("};")
    print("\nconst int g_staticdata_type_count = %d;" % len(rows))
    print("\n// Types with no m_TypeIndex symbol in this build (%d):" % len(missing))
    for name, cls in missing:
        print("//   %-38s %s" % (name, cls))
    return 0

sys.exit(main())
