// Generated by tools/generate_resource_fields.py - do not edit.
// Field offsets computed from upstream GuidResources.h declaration order,
// using macOS (libc++) type sizes. See the generator for the size table.
#include "staticdata_fields.h"
#include <stddef.h>

static const ResourceField fields_ActionResource[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x2c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Error", 0x3c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "MaxLevel", 0x4c, RF_U32 },  // uint32_t
    { "MaxValue", 0x50, RF_F64 },  // double
    { "DiceType", 0x58, RF_U8 },  // DiceSizeId
    { "ReplenishType", 0x59, RF_U8 },  // ResourceReplenishType
    { "ShowOnActionResourcePanel", 0x5a, RF_BOOL },  // bool
    { "UpdatesSpellPowerLevel", 0x5b, RF_BOOL },  // bool
    { "PartyActionResource", 0x5c, RF_BOOL },  // bool
    { "IsSpellResource", 0x5d, RF_BOOL },  // bool
    { "IsHidden", 0x5e, RF_BOOL },  // bool
};
static const ResourceField fields_ClassDescription[] = {
    { "ParentGuid", 0x18, RF_GUID },  // Guid
    { "Name", 0x28, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x2c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Unused", 0x3c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "SubclassTitle", 0x4c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x5c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ProgressionTableUUID", 0x70, RF_GUID },  // Guid
    { "SoundClassType", 0x80, RF_FIXEDSTRING },  // FixedString
    { "PrimaryAbility", 0x84, RF_U8 },  // AbilityId
    { "SpellCastingAbility", 0x85, RF_U8 },  // AbilityId
    { "MustPrepareSpells", 0x86, RF_BOOL },  // bool
    { "CanLearnSpells", 0x87, RF_BOOL },  // bool
    { "HasGod", 0x88, RF_BOOL },  // bool
    { "IsDefaultForUseSpellAction", 0x89, RF_BOOL },  // bool
    { "Tags", 0xc0, RF_ARRAY_GUID },  // Array<Guid>
    { "ClassEquipment", 0xd0, RF_FIXEDSTRING },  // FixedString
    { "CharacterCreationPose", 0xd4, RF_FIXEDSTRING },  // FixedString
    { "LearningStrategy", 0xd8, RF_U8 },  // SpellLearningStrategy
    { "field_71", 0xd9, RF_U8 },  // uint8_t
    { "BaseHp", 0xdc, RF_I32 },  // int
    { "HpPerLevel", 0xe0, RF_I32 },  // int
    { "CommonHotbarColumns", 0xe4, RF_I32 },  // int
    { "ClassHotbarColumns", 0xe8, RF_I32 },  // int
    { "ItemsHotbarColumns", 0xec, RF_I32 },  // int
    { "AnimationSetPriority", 0xf0, RF_I32 },  // int
    { "MulticlassSpellcasterModifier", 0xf8, RF_F64 },  // double
    { "SpellList", 0x100, RF_GUID },  // Guid
};
static const ResourceField fields_Tag[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Description", 0x20, RF_STDSTRING },  // STDString
    { "Icon", 0x38, RF_FIXEDSTRING },  // FixedString
    { "Categories", 0x3c, RF_U32 },  // uint32_t
    { "Properties", 0x40, RF_U32 },  // uint32_t
    { "DisplayName", 0x44, RF_TRANSLATEDSTRING },  // TranslatedString
    { "DisplayDescription", 0x54, RF_TRANSLATEDSTRING },  // TranslatedString
};
static const ResourceField fields_Faction[] = {
    { "Faction", 0x18, RF_FIXEDSTRING },  // FixedString
    { "ParentGuid", 0x20, RF_GUID },  // Guid
};
static const ResourceField fields_Race[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x2c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "MergedInto", 0x40, RF_GUID },  // Guid
    { "ParentGuid", 0x50, RF_GUID },  // Guid
    { "DisplayTypeUUID", 0x60, RF_GUID },  // Guid
    { "Tags", 0x70, RF_ARRAY_GUID },  // Array<Guid>
    { "ProgressionTableUUID", 0x80, RF_GUID },  // Guid
    { "RaceSoundSwitch", 0x90, RF_FIXEDSTRING },  // FixedString
    { "RaceEquipment", 0x94, RF_FIXEDSTRING },  // FixedString
    { "HairColors", 0x98, RF_ARRAY_GUID },  // Array<Guid>
    { "SkinColors", 0xa8, RF_ARRAY_GUID },  // Array<Guid>
    { "EyeColors", 0xb8, RF_ARRAY_GUID },  // Array<Guid>
    { "TattooColors", 0xc8, RF_ARRAY_GUID },  // Array<Guid>
    { "MakeupColors", 0xd8, RF_ARRAY_GUID },  // Array<Guid>
    { "LipsMakeupColors", 0xe8, RF_ARRAY_GUID },  // Array<Guid>
    { "HairHighlightColors", 0xf8, RF_ARRAY_GUID },  // Array<Guid>
    { "HairGrayingColors", 0x108, RF_ARRAY_GUID },  // Array<Guid>
    { "HornColors", 0x118, RF_ARRAY_GUID },  // Array<Guid>
    { "HornTipColors", 0x128, RF_ARRAY_GUID },  // Array<Guid>
    { "Visuals", 0x138, RF_ARRAY_GUID },  // Array<Guid>
    { "Gods", 0x148, RF_ARRAY_GUID },  // Array<Guid>
    { "ExcludedGods", 0x158, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_Origin[] = {
    { "AvailableInCharacterCreation", 0x18, RF_U8 },  // uint8_t
    { "Name", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x20, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "BodyType", 0x40, RF_U8 },  // uint8_t
    { "BodyShape", 0x41, RF_U8 },  // uint8_t
    { "LockBody", 0x42, RF_BOOL },  // bool
    { "RaceUUID", 0x48, RF_GUID },  // Guid
    { "SubRaceUUID", 0x58, RF_GUID },  // Guid
    { "LockRace", 0x68, RF_BOOL },  // bool
    { "BackgroundUUID", 0x70, RF_GUID },  // Guid
    { "GodUUID", 0x80, RF_GUID },  // Guid
    { "ClassUUID", 0x90, RF_GUID },  // Guid
    { "SubClassUUID", 0xa0, RF_GUID },  // Guid
    { "LockClass", 0xb0, RF_BOOL },  // bool
    { "GlobalTemplate", 0xb8, RF_GUID },  // Guid
    { "DefaultsTemplate", 0xc8, RF_GUID },  // Guid
    { "Passives", 0xd8, RF_STDSTRING },  // STDString
    { "AppearanceTags", 0x100, RF_ARRAY_GUID },  // Array<Guid>
    { "ReallyTags", 0x110, RF_ARRAY_GUID },  // Array<Guid>
    { "Flags", 0x120, RF_U32 },  // uint32_t
    { "Overview", 0x128, RF_STDSTRING },  // STDString
    { "CloseUpA", 0x140, RF_STDSTRING },  // STDString
    { "CloseUpB", 0x158, RF_STDSTRING },  // STDString
    { "ClassEquipmentOverride", 0x170, RF_FIXEDSTRING },  // FixedString
    { "VoiceTableUUID", 0x178, RF_GUID },  // Guid
    { "IntroDialogUUID", 0x188, RF_GUID },  // Guid
    { "IsHenchman", 0x198, RF_BOOL },  // bool
    { "Identity", 0x199, RF_U8 },  // uint8_t
    { "ExcludesOriginUUID", 0x1a0, RF_GUID },  // Guid
};
static const ResourceField fields_Background[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x28, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Passives", 0x38, RF_STDSTRING },  // STDString
    { "Tags", 0x60, RF_ARRAY_GUID },  // Array<Guid>
    { "Hidden", 0x70, RF_BOOL },  // bool
};
static const ResourceField fields_God[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x2c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Tags", 0x40, RF_ARRAY_GUID },  // Array<Guid>
    { "MergedInto", 0x50, RF_GUID },  // Guid
};
static const ResourceField fields_Progression[] = {
    { "SpellUUID", 0x18, RF_GUID },  // Guid
    { "Amount", 0x28, RF_I32 },  // int32_t
    { "Arg3", 0x2c, RF_I32 },  // int32_t
    { "SelectorId", 0x30, RF_STDSTRING },  // STDString
    { "CastingAbility", 0x48, RF_U8 },  // AbilityId
    { "ActionResource", 0x50, RF_GUID },  // Guid
    { "PrepareType", 0x60, RF_U8 },  // SpellPrepareType
    { "CooldownType", 0x61, RF_U8 },  // SpellCooldownType
    { "ClassUUID", 0x68, RF_GUID },  // Guid
    { "SpellUUID", 0x78, RF_GUID },  // Guid
    { "SelectorId", 0x88, RF_STDSTRING },  // STDString
    { "Ability", 0xa0, RF_U8 },  // AbilityId
    { "ActionResource", 0xa8, RF_GUID },  // Guid
    { "PrepareType", 0xb8, RF_U8 },  // SpellPrepareType
    { "CooldownType", 0xb9, RF_U8 },  // SpellCooldownType
    { "ClassUUID", 0xc0, RF_GUID },  // Guid
    { "UUID", 0xd0, RF_GUID },  // Guid
    { "Arg2", 0xe0, RF_I32 },  // int32_t
    { "Arg3", 0xe4, RF_I32 },  // int32_t
    { "Arg4", 0xe8, RF_STDSTRING },  // STDString
    { "UUID", 0x100, RF_GUID },  // Guid
    { "Amount", 0x110, RF_I32 },  // int32_t
    { "Amounts", 0x118, RF_ARRAY_I32 },  // Array<int32_t>
    { "BonusType", 0x128, RF_STDSTRING },  // STDString
    { "UUID", 0x140, RF_GUID },  // Guid
    { "Amount", 0x150, RF_I32 },  // int32_t
    { "Arg3", 0x158, RF_STDSTRING },  // STDString
    { "UUID", 0x170, RF_GUID },  // Guid
    { "Amount", 0x180, RF_I32 },  // int32_t
    { "Arg3", 0x184, RF_BOOL },  // bool
    { "Arg4", 0x188, RF_STDSTRING },  // STDString
    { "UUID", 0x1a0, RF_GUID },  // Guid
    { "Amount", 0x1b0, RF_I32 },  // int32_t
    { "Amount2", 0x1b4, RF_I32 },  // int32_t
    { "Arg3", 0x1b8, RF_STDSTRING },  // STDString
    { "UUID", 0x1d0, RF_GUID },  // Guid
    { "Amount", 0x1e0, RF_I32 },  // int32_t
    { "Arg3", 0x1e8, RF_STDSTRING },  // STDString
    { "TableUUID", 0x200, RF_GUID },  // Guid
    { "Name", 0x210, RF_STDSTRING },  // STDString
    { "SubClasses", 0x228, RF_ARRAY_GUID },  // Array<Guid>
    { "PassivesAdded", 0x248, RF_STDSTRING },  // STDString
    { "PassivesRemoved", 0x270, RF_STDSTRING },  // STDString
    { "BoostPrototypes", 0x288, RF_ARRAY_GUID },  // Array<Guid>
    { "Boosts", 0x298, RF_STDSTRING },  // STDString
    { "ProgressionType", 0x2b0, RF_U8 },  // ProgressionType
    { "Level", 0x2b1, RF_U8 },  // uint8_t
    { "AllowImprovement", 0x2b2, RF_BOOL },  // bool
    { "field_D0", 0x2b8, RF_ARRAY_FIXEDSTRING },  // Array<FixedString>
    { "IsMulticlass", 0x2c8, RF_BOOL },  // bool
};
static const ResourceField fields_ProgressionDescription[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x28, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Hidden", 0x38, RF_BOOL },  // bool
    { "ExactMatch", 0x3c, RF_FIXEDSTRING },  // FixedString
    { "Type", 0x40, RF_FIXEDSTRING },  // FixedString
    { "ParamMatch", 0x44, RF_FIXEDSTRING },  // FixedString
    { "ProgressionId", 0x48, RF_GUID },  // Guid
    { "ProgressionTableId", 0x58, RF_GUID },  // Guid
    { "SelectorId", 0x68, RF_FIXEDSTRING },  // FixedString
    { "PassivePrototype", 0x6c, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_Gossip[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Type", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "Priority", 0x20, RF_I32 },  // int
    { "ConditionFlags", 0x28, RF_ARRAY_GUID },  // Array<Guid>
    { "ResultFlags", 0x38, RF_ARRAY_GUID },  // Array<Guid>
    { "DialogUUID", 0x48, RF_GUID },  // Guid
};
static const ResourceField fields_ActionResourceGroup[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "field_38", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "field_48", 0x40, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ActionResourceDefinitions", 0x50, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_Color[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
};
static const ResourceField fields_EquipmentType[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "WeaponType_OneHanded", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "WeaponType_TwoHanded", 0x20, RF_FIXEDSTRING },  // FixedString
    { "BoneMainSheathed", 0x24, RF_FIXEDSTRING },  // FixedString
    { "BoneMainUnsheathed", 0x28, RF_FIXEDSTRING },  // FixedString
    { "BoneOffHandSheathed", 0x2c, RF_FIXEDSTRING },  // FixedString
    { "BoneOffHandUnsheathed", 0x30, RF_FIXEDSTRING },  // FixedString
    { "BoneVersatileSheathed", 0x34, RF_FIXEDSTRING },  // FixedString
    { "BoneVersatileUnsheathed", 0x38, RF_FIXEDSTRING },  // FixedString
    { "SourceBoneSheathed", 0x3c, RF_FIXEDSTRING },  // FixedString
    { "SourceBoneVersatileSheathed", 0x40, RF_FIXEDSTRING },  // FixedString
    { "SourceBoneVersatileUnsheathed", 0x44, RF_FIXEDSTRING },  // FixedString
    { "SourceBoneAlternativeUnsheathed", 0x48, RF_FIXEDSTRING },  // FixedString
    { "SoundAttackType", 0x4c, RF_FIXEDSTRING },  // FixedString
    { "SoundEquipmentType", 0x50, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_Flag[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Description", 0x20, RF_STDSTRING },  // STDString
    { "Usage", 0x38, RF_U8 },  // uint8_t
};
static const ResourceField fields_Feat[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Requirements", 0x20, RF_STDSTRING },  // STDString
    { "PassivesAdded", 0x48, RF_STDSTRING },  // STDString
    { "PassivesRemoved", 0x70, RF_STDSTRING },  // STDString
    { "Boosts", 0x98, RF_STDSTRING },  // STDString
    { "BoostPrototypes", 0xb0, RF_ARRAY_GUID },  // Array<Guid>
    { "CanBeTakenMultipleTimes", 0xc0, RF_BOOL },  // bool
};
static const ResourceField fields_FeatDescription[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x28, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Hidden", 0x38, RF_BOOL },  // bool
    { "ExactMatch", 0x3c, RF_FIXEDSTRING },  // FixedString
    { "Type", 0x40, RF_FIXEDSTRING },  // FixedString
    { "ParamMatch", 0x44, RF_FIXEDSTRING },  // FixedString
    { "FeatId", 0x48, RF_GUID },  // Guid
    { "SelectorId", 0x58, RF_FIXEDSTRING },  // FixedString
    { "PassivePrototype", 0x5c, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_PassiveList[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Passives", 0x20, RF_ARRAY_FIXEDSTRING },  // Array<FixedString>
    { "MergedInto", 0x30, RF_GUID },  // Guid
};
static const ResourceField fields_SkillList[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "MergedInto", 0x30, RF_GUID },  // Guid
};
static const ResourceField fields_SpellList[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "MergedInto", 0x50, RF_GUID },  // Guid
};
static const ResourceField fields_AbilityList[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "MergedInto", 0x30, RF_GUID },  // Guid
};
static const ResourceField fields_CompanionPreset[] = {
    { "RaceUuid", 0x18, RF_GUID },  // Guid
    { "SubRaceUuid", 0x28, RF_GUID },  // Guid
    { "BodyType", 0x38, RF_U8 },  // uint8_t
    { "BodyShape", 0x39, RF_U8 },  // uint8_t
    { "RootTemplate", 0x40, RF_GUID },  // Guid
    { "Overview", 0x50, RF_STDSTRING },  // STDString
    { "CloseUpA", 0x68, RF_STDSTRING },  // STDString
    { "CloseUpB", 0x80, RF_STDSTRING },  // STDString
    { "VoiceTableUuid", 0x98, RF_GUID },  // Guid
    { "VOLinesTableUuid", 0xa8, RF_GUID },  // Guid
};
static const ResourceField fields_AbilityDistributionPreset[] = {
    { "ClassUuid", 0x18, RF_GUID },  // Guid
    { "field_28", 0x28, RF_I32 },  // int
    { "Strength", 0x2c, RF_I32 },  // int
    { "Dexterity", 0x30, RF_I32 },  // int
    { "Constitution", 0x34, RF_I32 },  // int
    { "Intelligence", 0x38, RF_I32 },  // int
    { "Wisdom", 0x3c, RF_I32 },  // int
    { "Charisma", 0x40, RF_I32 },  // int
};
static const ResourceField fields_CharacterCreationAccessorySet[] = {
    { "CharacterCreationSet", 0x18, RF_BOOL },  // bool
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "VisualUUID", 0x30, RF_ARRAY_GUID },  // Array<Guid>
    { "SlotName", 0x40, RF_FIXEDSTRING },  // FixedString
    { "RaceUUID", 0x48, RF_GUID },  // Guid
    { "DefaultForRootTemplates", 0x58, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_CharacterCreationAppearanceMaterial[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "MaterialPresetUUID", 0x30, RF_GUID },  // Guid
    { "MaterialType", 0x40, RF_U32 },  // AppearanceMaterialType
    { "MaterialTypeName", 0x44, RF_FIXEDSTRING },  // FixedString
    { "MaleRootTemplate", 0x58, RF_GUID },  // Guid
    { "MaleCameraName", 0x68, RF_FIXEDSTRING },  // FixedString
    { "FemaleRootTemplate", 0x70, RF_GUID },  // Guid
    { "FemaleCameraName", 0x80, RF_FIXEDSTRING },  // FixedString
    { "DragonbornMaleRootTemplate", 0x88, RF_GUID },  // Guid
    { "DragonbornFemaleRootTemplate", 0x98, RF_GUID },  // Guid
};
static const ResourceField fields_CharacterCreationAppearanceVisual[] = {
    { "RootTemplate", 0x18, RF_GUID },  // Guid
    { "RaceUUID", 0x28, RF_GUID },  // Guid
    { "BodyType", 0x38, RF_U8 },  // uint8_t
    { "BodyShape", 0x39, RF_U8 },  // uint8_t
    { "field_3C", 0x3c, RF_U32 },  // uint32_t
    { "SlotName", 0x40, RF_FIXEDSTRING },  // FixedString
    { "VisualResource", 0x48, RF_GUID },  // Guid
    { "HeadAppearanceUUID", 0x58, RF_GUID },  // Guid
    { "DefaultSkinColor", 0x68, RF_GUID },  // Guid
    { "DisplayName", 0x78, RF_TRANSLATEDSTRING },  // TranslatedString
    { "IconIdOverride", 0x88, RF_FIXEDSTRING },  // FixedString
    { "DefaultForBodyType", 0x8c, RF_U8 },  // uint8_t
    { "TextureEntryPart", 0x90, RF_FIXEDSTRING },  // FixedString
    { "Tags", 0x98, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_CharacterCreationEquipmentIcons[] = {
    { "RootTemplate", 0x18, RF_GUID },  // Guid
    { "EquipmentTemplate", 0x28, RF_GUID },  // Guid
    { "AnimationUUID", 0x38, RF_GUID },  // Guid
    { "IconGenerationTrigger", 0x48, RF_FIXEDSTRING },  // FixedString
    { "SlotName", 0x4c, RF_FIXEDSTRING },  // FixedString
    { "MeshIsTwoSided", 0x50, RF_BOOL },  // bool
};
static const ResourceField fields_CharacterCreationIconSettings[] = {
    { "RootTemplate", 0x18, RF_GUID },  // Guid
    { "BodyShape", 0x28, RF_U8 },  // uint8_t
    { "HeadAppearanceUUID", 0x30, RF_GUID },  // Guid
};
static const ResourceField fields_CharacterCreationColor[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "MaterialPresetUUID", 0x30, RF_GUID },  // Guid
    { "SkinType", 0x50, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_CharacterCreationMaterialOverride[] = {
    { "MaterialType", 0x18, RF_U32 },  // AppearanceMaterialType
    { "ActiveMaterialPresetUUID", 0x20, RF_GUID },  // Guid
    { "InactiveMaterialPresetUUID", 0x30, RF_GUID },  // Guid
    { "SourceMaterialUUID", 0x40, RF_FIXEDSTRING },  // FixedString
    { "TargetMaterialUUID", 0x44, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_CharacterCreationPassiveAppearance[] = {
    { "Passive", 0x18, RF_FIXEDSTRING },  // FixedString
    { "RaceUUID", 0x20, RF_GUID },  // Guid
    { "AppearanceMaterialUUIDs", 0x30, RF_ARRAY_GUID },  // Array<Guid>
    { "ColorMaterialUUIDs", 0x40, RF_ARRAY_GUID },  // Array<Guid>
    { "AccessorySetUUIDs", 0x50, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_CharacterCreationPreset[] = {
    { "RaceUUID", 0x18, RF_GUID },  // Guid
    { "SubRaceUUID", 0x28, RF_GUID },  // Guid
    { "BodyType", 0x38, RF_U8 },  // uint8_t
    { "BodyShape", 0x39, RF_U8 },  // uint8_t
    { "RootTemplate", 0x40, RF_GUID },  // Guid
    { "Overview", 0x50, RF_STDSTRING },  // STDString
    { "CloseUpA", 0x68, RF_STDSTRING },  // STDString
    { "CloseUpB", 0x80, RF_STDSTRING },  // STDString
    { "VOLinesTableUUID", 0x98, RF_GUID },  // Guid
};
static const ResourceField fields_CharacterCreationSharedVisual[] = {
    { "SlotName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "VisualResource", 0x20, RF_GUID },  // Guid
    { "BoneName", 0x30, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x34, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Tags", 0x48, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_LevelMap[] = {
    { "DiceValue", 0x18, RF_U8 },  // DiceSizeId
    { "AmountOfDices", 0x19, RF_U8 },  // uint8_t
    { "Name", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "PreferredClassUUID", 0x20, RF_GUID },  // Guid
};
static const ResourceField fields_ApprovalRating[] = {
    { "id", 0x18, RF_GUID },  // Guid
    { "value", 0x28, RF_I32 },  // int32_t
    { "Scope", 0x2c, RF_U8 },  // uint8_t
};
static const ResourceField fields_AreaLevelOverride[] = {
    { "ParentUuid", 0x18, RF_GUID },  // Guid
    { "EntityLevel", 0x28, RF_I32 },  // int32_t
    { "TreasureLevel", 0x2c, RF_I32 },  // int32_t
};
static const ResourceField fields_AvatarContainerTemplates[] = {
    { "TemplateId", 0x18, RF_GUID },  // Guid
};
static const ResourceField fields_BackgroundGoal[] = {
    { "Title", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x28, RF_TRANSLATEDSTRING },  // TranslatedString
    { "BackgroundUuid", 0x38, RF_GUID },  // Guid
    { "InspirationPoints", 0x48, RF_I32 },  // int32_t
    { "RewardLevel", 0x4c, RF_I32 },  // int32_t
    { "ExperienceReward", 0x50, RF_GUID },  // Guid
};
static const ResourceField fields_CalendarDayRange[] = {
    { "Start", 0x18, RF_I32 },  // int32_t
    { "End", 0x1c, RF_I32 },  // int32_t
    { "LeapYearStart", 0x20, RF_I32 },  // int32_t
    { "LeapYearEnd", 0x24, RF_I32 },  // int32_t
    { "Name", 0x28, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x2c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "DisplayCommonName", 0x3c, RF_TRANSLATEDSTRING },  // TranslatedString
};
static const ResourceField fields_CampChestTemplate[] = {
    { "TemplateId", 0x18, RF_GUID },  // Guid
};
static const ResourceField fields_DefaultValueGuidResource[] = {
    { "TableUUID", 0x18, RF_GUID },  // Guid
    { "OriginUuid", 0x28, RF_GUID },  // Guid
    { "RaceUuid", 0x38, RF_GUID },  // Guid
    { "ClassUuid", 0x48, RF_GUID },  // Guid
    { "SubclassUuid", 0x58, RF_GUID },  // Guid
    { "Level", 0x68, RF_I32 },  // int32_t
    { "SelectorId", 0x70, RF_STDSTRING },  // STDString
};
static const ResourceField fields_CharacterCreationVOLine[] = {
    { "VoiceLine", 0x18, RF_FIXEDSTRING },  // FixedString
    { "TableUuid", 0x20, RF_GUID },  // Guid
};
static const ResourceField fields_CinematicArenaFrequencyGroup[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "MaxFrequency", 0x1c, RF_F32 },  // float
    { "PercentageChance", 0x20, RF_F64 },  // double
};
static const ResourceField fields_CustomDiceTemplate[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "FontColour", 0x30, RF_STDSTRING },  // STDString
    { "DisplayNamme", 0x48, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x58, RF_TRANSLATEDSTRING },  // TranslatedString
    { "IsDefault", 0x68, RF_BOOL },  // bool
    { "Flip1", 0x69, RF_BOOL },  // bool
    { "Flip20", 0x6a, RF_BOOL },  // bool
    { "Icon", 0x6b, RF_BOOL },  // bool
    { "Icon20", 0x6c, RF_BOOL },  // bool
};
static const ResourceField fields_ConditionErrorDescription[] = {
    { "Identifier", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DisplayName", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ErrorDescriptionType", 0x2c, RF_U8 },  // uint8_t
    { "Hidden", 0x2d, RF_BOOL },  // bool
};
static const ResourceField fields_DeathTypeEffect[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "ParentUuid", 0x30, RF_GUID },  // Guid
    { "Fallback", 0x40, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_DifficultyClass[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "Difficulties", 0x30, RF_ARRAY_I32 },  // Array<int32_t>
    { "field_40", 0x40, RF_U8 },  // uint8_t
};
static const ResourceField fields_DisturbanceProperty[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_DLC[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "SteamAPICode", 0x30, RF_U32 },  // uint32_t
    { "GalaxyAPICode", 0x34, RF_U32 },  // uint32_t
    { "PS5APICode", 0x38, RF_U32 },  // uint32_t
    { "XLiveAPICode", 0x3c, RF_U32 },  // uint32_t
    { "TwitchAPICode", 0x40, RF_U32 },  // uint32_t
    { "CustomDice", 0x48, RF_GUID },  // Guid
    { "UnlockType", 0x58, RF_U8 },  // uint8_t
};
static const ResourceField fields_EncumbranceType[] = {
    { "Status", 0x18, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_EquipmentList[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Items", 0x20, RF_ARRAY_FIXEDSTRING },  // Array<FixedString>
    { "MergedInto", 0x30, RF_GUID },  // Guid
};
static const ResourceField fields_ExperienceRewards[] = {
    { "RewardType", 0x18, RF_U8 },  // uint8_t
    { "LevelSource", 0x19, RF_U8 },  // uint8_t
    { "Name", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "PerLevelRewards", 0x20, RF_ARRAY_I32 },  // Array<int32_t>
};
static const ResourceField fields_FeatSoundState[] = {
    { "FeatName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "FeatUuid", 0x20, RF_GUID },  // Guid
    { "OverrideSwitchGroup", 0x30, RF_FIXEDSTRING },  // FixedString
    { "OverrideSwitch", 0x34, RF_FIXEDSTRING },  // FixedString
    { "DefaultSwitch", 0x38, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_FlagSoundState[] = {
    { "FlagName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "FlagUuid", 0x20, RF_GUID },  // Guid
    { "OverrideSwitchGroup", 0x30, RF_FIXEDSTRING },  // FixedString
    { "OverrideSwitch", 0x34, RF_FIXEDSTRING },  // FixedString
    { "DefaultSwitch", 0x38, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_GoldRewards[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "ParentUuid", 0x20, RF_GUID },  // Guid
    { "ParentScale", 0x30, RF_F64 },  // double
    { "PerLevelRewards", 0x38, RF_ARRAY_I32 },  // Array<int32_t>
};
static const ResourceField fields_FixedHotBarSlot[] = {
    { "SlotIndex", 0x18, RF_I32 },  // int32_t
    { "SpellId", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "HotBarController", 0x20, RF_U8 },  // uint8_t
    { "HotBarType", 0x21, RF_U8 },  // uint8_t
};
static const ResourceField fields_ItemThrowParams[] = {
    { "Priority", 0x18, RF_I32 },  // int32_t
    { "Conditions", 0x20, RF_STDSTRING },  // STDString
    { "MaxDistForOneRotation", 0x38, RF_I32 },  // int32_t
    { "MaxDistForTwoRotations", 0x3c, RF_I32 },  // int32_t
    { "MaxDistForZeroRotations", 0x40, RF_I32 },  // int32_t
    { "RotationAxis", 0x50, RF_U32 },  // uint32_t
};
static const ResourceField fields_ItemWallTemplate[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "HighLeft", 0x30, RF_STDSTRING },  // STDString
    { "HighMiddle", 0x48, RF_STDSTRING },  // STDString
    { "HighRight", 0x60, RF_STDSTRING },  // STDString
    { "LowLeft", 0x78, RF_STDSTRING },  // STDString
    { "LowMiddle", 0x90, RF_STDSTRING },  // STDString
    { "LowRight", 0xa8, RF_STDSTRING },  // STDString
    { "Padding", 0xc0, RF_F32 },  // float
    { "RandomRotation", 0xc4, RF_BOOL },  // bool
    { "Animation", 0xc8, RF_FIXEDSTRING },  // FixedString
    { "TimeBetweenItems", 0xcc, RF_F32 },  // float
};
static const ResourceField fields_TrajectoryRule[] = {
    { "Template", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Priority", 0x1c, RF_I32 },  // int32_t
    { "HeightMin", 0x20, RF_F32 },  // float
    { "HeightMax", 0x24, RF_F32 },  // float
    { "LengthMin", 0x28, RF_F32 },  // float
    { "LengthMax", 0x2c, RF_F32 },  // float
};
static const ResourceField fields_LimbsMapping[] = {
    { "RootTemplate", 0x18, RF_GUID },  // Guid
    { "BackRight", 0x28, RF_ARRAY_U8 },  // Array<uint8_t>
    { "BackLeft", 0x38, RF_ARRAY_U8 },  // Array<uint8_t>
    { "FrontRight", 0x48, RF_ARRAY_U8 },  // Array<uint8_t>
    { "FrontLeft", 0x58, RF_ARRAY_U8 },  // Array<uint8_t>
};
static const ResourceField fields_LongRestCost[] = {
    { "CampQuality", 0x18, RF_U32 },  // uint32_t
    { "RequiredSupplies", 0x1c, RF_I32 },  // int32_t
    { "CampGrowthDifficulty", 0x20, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_ManagedStatusVFX[] = {
    { "Group", 0x18, RF_FIXEDSTRING },  // FixedString
    { "PositiveEffect", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "NegativeEffect", 0x20, RF_FIXEDSTRING },  // FixedString
    { "MixedEffect", 0x24, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_MultiEffectInfo[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
};
static const ResourceField fields_OriginIntroEntity[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "PlayerIndex", 0x1c, RF_I32 },  // int32_t
    { "DummyUuid", 0x20, RF_GUID },  // Guid
};
static const ResourceField fields_PassivesVFX[] = {
    { "PassiveName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "PrepareEffect", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "CastEffect", 0x20, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_ProjectileDefault[] = {
    { "ProjectileDefaultType", 0x18, RF_U8 },  // uint8_t
    { "ProjectileTemplateId", 0x20, RF_GUID },  // Guid
};
static const ResourceField fields_RandomCastOutcome[] = {
    { "GroupName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Spell", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "Level", 0x20, RF_I32 },  // int32_t
    { "ClassUuid", 0x28, RF_GUID },  // Guid
    { "ClassLevel", 0x38, RF_I32 },  // int32_t
};
static const ResourceField fields_SoundSpellTrajectoryRule[] = {
    { "RuleName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "CurveUuid", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "SoundEvent", 0x20, RF_FIXEDSTRING },  // FixedString
    { "DistancePastListener", 0x24, RF_F32 },  // float
};
static const ResourceField fields_StatusSoundState[] = {
    { "SoundStateName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "CombatVocalOverrideSwitch", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "SpellOverrideSwitchGroup", 0x20, RF_FIXEDSTRING },  // FixedString
    { "SpellOverrideSwitchState", 0x24, RF_FIXEDSTRING },  // FixedString
    { "SpellOverrideSwitchClearState", 0x28, RF_FIXEDSTRING },  // FixedString
    { "BlockVocals", 0x2c, RF_BOOL },  // bool
};
static const ResourceField fields_SurfaceCursorMessage[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "CursorMessage", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Priority", 0x2c, RF_I32 },  // int
};
static const ResourceField fields_TadpolePower[] = {
    { "Prerequisites", 0x18, RF_ARRAY_GUID },  // Array<Guid>
    { "Name", 0x28, RF_FIXEDSTRING },  // FixedString
    { "NeedsHalfIllithidToUnlock", 0x2c, RF_BOOL },  // bool
};
static const ResourceField fields_TagSoundState[] = {
    { "TagName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "TagUuid", 0x20, RF_GUID },  // Guid
    { "OverrideSwitchGroup", 0x30, RF_FIXEDSTRING },  // FixedString
    { "OverrideSwitch", 0x34, RF_FIXEDSTRING },  // FixedString
    { "DefaultSwitch", 0x38, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_TooltipExtraText[] = {
    { "Text", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
};
static const ResourceField fields_TooltipUpcastDescription[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Text", 0x1c, RF_TRANSLATEDSTRING },  // TranslatedString
};
static const ResourceField fields_TutorialEntry[] = {
    { "DisplayTitle", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "KeyboardDescription", 0x28, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ControllerDescription", 0x38, RF_TRANSLATEDSTRING },  // TranslatedString
    { "KeyboardVideo", 0x48, RF_STDSTRING },  // STDString
    { "ControllerVideo", 0x60, RF_STDSTRING },  // STDString
    { "Section", 0x78, RF_U8 },  // uint8_t
    { "InputType", 0x79, RF_U8 },  // uint8_t
    { "Hidden", 0x7a, RF_BOOL },  // bool
};
static const ResourceField fields_TutorialModalEntry[] = {
    { "TutorialName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "TutorialID", 0x1c, RF_I32 },  // int32_t
    { "DisplayTitle", 0x20, RF_TRANSLATEDSTRING },  // TranslatedString
    { "KeyboardDescription", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ControllerDescription", 0x40, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Section", 0x50, RF_U8 },  // uint8_t
    { "ModalType", 0x51, RF_U8 },  // uint8_t
    { "WaitForEndDialog", 0x52, RF_BOOL },  // bool
    { "WaitForEndCC", 0x53, RF_BOOL },  // bool
    { "ExtraData", 0x54, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_TutorialUnifiedEntry[] = {
    { "TutorialName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "ModalType", 0x1c, RF_U8 },  // uint8_t
    { "DisplayTitle", 0x20, RF_TRANSLATEDSTRING },  // TranslatedString
    { "KeyboardDescription", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ControllerDescription", 0x40, RF_TRANSLATEDSTRING },  // TranslatedString
    { "KeyboardJournalDescription", 0x50, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ControllerJournalDescription", 0x60, RF_TRANSLATEDSTRING },  // TranslatedString
    { "KeyboardInputList", 0x70, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ControllerInputList", 0x80, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Section", 0x90, RF_U8 },  // uint8_t
    { "WaitForEndDialog", 0x91, RF_BOOL },  // bool
    { "WaitForEndCC", 0x92, RF_BOOL },  // bool
    { "WaitForLayers", 0x93, RF_BOOL },  // bool
    { "ShowInSplitScreen", 0x94, RF_BOOL },  // bool
    { "InputType", 0x95, RF_U8 },  // uint8_t
    { "field_98", 0x98, RF_U32 },  // uint32_t
    { "Icon", 0xa0, RF_STDSTRING },  // STDString
    { "LifeTime", 0xb8, RF_I32 },  // int32_t
    { "PositionOffsetX", 0xbc, RF_I32 },  // int32_t
    { "PositionOffsetY", 0xc0, RF_I32 },  // int32_t
};
static const ResourceField fields_TutorialEvent[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "EventType", 0x30, RF_U8 },  // uint8_t
    { "ActionResource", 0x38, RF_GUID },  // Guid
    { "HotbarSlotFlags", 0x48, RF_U32 },  // uint32_t
    { "UserAction", 0x4c, RF_U8 },  // uint8_t
};
static const ResourceField fields_VFX[] = {
    { "VFXGameplayName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "VFXEffectName", 0x1c, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_Voice[] = {
    { "TableUuid", 0x18, RF_GUID },  // Guid
    { "DisplayName", 0x28, RF_TRANSLATEDSTRING },  // TranslatedString
    { "SpeakerUuid", 0x38, RF_GUID },  // Guid
    { "BodyType", 0x48, RF_U8 },  // uint8_t
    { "Tags", 0x50, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_WeaponAnimationSet[] = {
    { "MainHand", 0x18, RF_FIXEDSTRING },  // FixedString
    { "OffHand", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "AnimationSetUuid", 0x20, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_WeightCategories[] = {
    { "MaxWeight", 0x18, RF_I32 },  // int32_t
    { "Tags", 0x20, RF_ARRAY_GUID },  // Array<Guid>
    { "ObjectSize", 0x30, RF_U8 },  // uint8_t
};
static const ResourceField fields_ShapeshiftRule[] = {
    { "Type", 0x18, RF_U8 },  // uint8_t
    { "Value", 0x1c, RF_I32 },  // int32_t
    { "Type", 0x20, RF_U8 },  // uint8_t
    { "Value", 0x24, RF_F32 },  // float
    { "RuleName", 0x28, RF_STDSTRING },  // STDString
    { "WildShapeHotBar", 0x50, RF_BOOL },  // bool
    { "FootstepsType", 0x5c, RF_U8 },  // uint8_t
    { "RemoveOldTags", 0x70, RF_BOOL },  // bool
    { "ApplyTagsFromTemplate", 0x71, RF_BOOL },  // bool
    { "TagsAdd", 0x78, RF_ARRAY_GUID },  // Array<Guid>
    { "TagsRemove", 0x88, RF_ARRAY_GUID },  // Array<Guid>
    { "ActionCapabilities", 0x98, RF_U16 },  // uint16_t
    { "InteractionsCapabilities", 0x9a, RF_U16 },  // uint16_t
    { "AwarenessCapabilities", 0x9c, RF_U16 },  // uint16_t
    { "SpeakingCapabilities", 0x9e, RF_U16 },  // uint16_t
    { "ChangeRace", 0xa0, RF_BOOL },  // bool
    { "ChangeBodyType", 0xa1, RF_BOOL },  // bool
    { "UseShapeshiftIdentity", 0xa2, RF_BOOL },  // bool
    { "ChangeAi", 0xa3, RF_BOOL },  // bool
    { "ApplyVisual", 0xc8, RF_BOOL },  // bool
    { "ApplyVisualInCC", 0xc9, RF_BOOL },  // bool
    { "IgnoreCustomLooks", 0xca, RF_BOOL },  // bool
    { "RetainDisplayName", 0xcb, RF_BOOL },  // bool
    { "ChangeIcon", 0xcc, RF_BOOL },  // bool
    { "MuteEquipmentSound", 0xd8, RF_BOOL },  // bool
    { "OverrideSpeaker", 0xd9, RF_BOOL },  // bool
    { "RemovePrevSpells", 0xda, RF_BOOL },  // bool
    { "ApplySpellsFromTemplate", 0xdb, RF_BOOL },  // bool
    { "SpellsAdd", 0xe0, RF_ARRAY_FIXEDSTRING },  // Array<FixedString>
    { "SpellsRemove", 0xf0, RF_ARRAY_FIXEDSTRING },  // Array<FixedString>
    { "RetainCanSeeThrough", 0x100, RF_BOOL },  // bool
    { "RetainCanShootThrough", 0x101, RF_BOOL },  // bool
    { "RetainCanWalkThrough", 0x102, RF_BOOL },  // bool
    { "BaseACOverride", 0x103, RF_BOOL },  // bool
    { "UnarmedAbilityFromTemplate", 0x104, RF_BOOL },  // bool
    { "DisableEquipmentSlots", 0x105, RF_BOOL },  // bool
    { "UseTemplateEquipmentSet", 0x106, RF_BOOL },  // bool
    { "KillEntityAtZeroHP", 0x107, RF_BOOL },  // bool
    { "PathInfluence", 0x108, RF_STDSTRING },  // STDString
    { "BlockLevelUp", 0x138, RF_BOOL },  // bool
    { "FlagsInheritanceType", 0x139, RF_U8 },  // uint8_t
    { "DefaultBoostsInheritanceType", 0x13a, RF_U8 },  // uint8_t
    { "PersonalStatusImmunitiesInheritanceType", 0x13b, RF_U8 },  // uint8_t
    { "SpellCastingAbilityInheritanceType", 0x13c, RF_U8 },  // uint8_t
    { "PassivesInheritanceType", 0x13d, RF_U8 },  // uint8_t
    { "ResistancesInheritanceType", 0x13e, RF_U8 },  // uint8_t
    { "DifficultyStatusesInheritanceType", 0x13f, RF_U8 },  // uint8_t
    { "ProficiencyGroupsInheritanceType", 0x140, RF_U8 },  // uint8_t
    { "BloodSurfaceTypeInheritanceType", 0x141, RF_U8 },  // uint8_t
    { "HitBloodTypeInheritanceType", 0x142, RF_U8 },  // uint8_t
    { "DeathActionsInheritanceType", 0x143, RF_U8 },  // uint8_t
};
static const ResourceField fields_AnimationSetPriority[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "Priority", 0x30, RF_I32 },  // int32_t
    { "AddidionalObjects", 0x38, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_SpellMetaCondition[] = {
    { "ConditionType", 0x18, RF_U8 },  // SpellMetaConditionType
    { "Filter", 0x20, RF_STDSTRING },  // STDString
    { "AdditionalConditions", 0x38, RF_STDSTRING },  // STDString
    { "OverrideOriginalCondition", 0x50, RF_BOOL },  // bool
};
static const ResourceField fields_ScriptMaterialParameterOverride[] = {
    { "ParameterName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "ParameterType", 0x1c, RF_FIXEDSTRING },  // FixedString
    { "SetMode", 0x20, RF_U8 },  // uint8_t
    { "IsFixedString", 0x21, RF_U8 },  // uint8_t
};
static const ResourceField fields_ScriptMaterialPresetOverride[] = {
    { "ParameterUuids", 0x18, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_VisualLocatorAttachment[] = {
    { "DisplayName", 0x18, RF_FIXEDSTRING },  // FixedString
    { "LocatorName", 0x1c, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_RulesetModifier[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "DisplayName", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x40, RF_TRANSLATEDSTRING },  // TranslatedString
    { "RulesetModifierType", 0x50, RF_U8 },  // uint8_t
    { "field_54", 0x54, RF_I32 },  // int
    { "Max", 0x58, RF_F32 },  // float
    { "Step", 0x5c, RF_F32 },  // float
    { "Default", 0x60, RF_STDSTRING },  // STDString
};
static const ResourceField fields_RulesetModifierOption[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "DisplayName", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x40, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Modifier", 0x50, RF_GUID },  // Guid
    { "Value", 0x60, RF_STDSTRING },  // STDString
};
static const ResourceField fields_Ruleset[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "Type", 0x30, RF_U8 },  // uint8_t
    { "DisplayName", 0x34, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x44, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Parent", 0x58, RF_ARRAY_GUID },  // Array<Guid>
    { "ShowInCustom", 0x68, RF_BOOL },  // bool
};
static const ResourceField fields_RulesetValue[] = {
    { "Ruleset", 0x18, RF_GUID },  // Guid
    { "Modifier", 0x28, RF_GUID },  // Guid
    { "RawValue", 0x38, RF_STDSTRING },  // STDString
};
static const ResourceField fields_RulesetSelectionPreset[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "Rulesets", 0x30, RF_ARRAY_GUID },  // Array<Guid>
    { "DisplayName", 0x40, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Description", 0x50, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Asset", 0x60, RF_STDSTRING },  // STDString
    { "IsCustom", 0x78, RF_BOOL },  // bool
};
static const ResourceField fields_OneTimeReward[] = {
    { "ItemTemplateId", 0x18, RF_FIXEDSTRING },  // FixedString
    { "Amount", 0x1c, RF_I32 },  // int
};
static const ResourceField fields_AnimationShortNameCategory[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_AnimationShortName[] = {
    { "Name", 0x18, RF_FIXEDSTRING },  // FixedString
    { "CategoryGuid", 0x20, RF_GUID },  // Guid
};
static const ResourceField fields_PhotoModeBlueprintOverride[] = {
    { "SourceBlueprintUUID", 0x18, RF_FIXEDSTRING },  // FixedString
    { "DummyBlueprintUUID", 0x1c, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_PhotoModeColourGrading[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Resource", 0x28, RF_FIXEDSTRING },  // FixedString
};
static const ResourceField fields_PhotoModeDecorFrame[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Asset", 0x28, RF_STDSTRING },  // STDString
    { "LeftSliceSize", 0x40, RF_F32 },  // float
    { "TopSliceSize", 0x44, RF_F32 },  // float
    { "RightSliceSize", 0x48, RF_F32 },  // float
    { "BottomSliceSize", 0x4c, RF_F32 },  // float
    { "IconWidth", 0x50, RF_F32 },  // float
};
static const ResourceField fields_PhotoModeEmoteAnimation[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "DisplayName", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ShortName", 0x40, RF_FIXEDSTRING },  // FixedString
    { "TagsFilter", 0x48, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_PhotoModeEmoteCollection[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "PosesList", 0x28, RF_ARRAY_GUID },  // Array<Guid>
    { "AnimationsList", 0x38, RF_ARRAY_GUID },  // Array<Guid>
    { "Name", 0x48, RF_STDSTRING },  // STDString
};
static const ResourceField fields_PhotoModeEmotePose[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "DisplayName", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ShortName", 0x40, RF_FIXEDSTRING },  // FixedString
    { "Timing", 0x44, RF_U32 },  // uint32_t
    { "TagsFilter", 0x48, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_PhotoModeFaceExpressionCollection[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "FaceExpressionsList", 0x28, RF_ARRAY_GUID },  // Array<Guid>
    { "Name", 0x38, RF_STDSTRING },  // STDString
};
static const ResourceField fields_PhotoModeFaceExpression[] = {
    { "Name", 0x18, RF_STDSTRING },  // STDString
    { "DisplayName", 0x30, RF_TRANSLATEDSTRING },  // TranslatedString
    { "ShortName", 0x40, RF_FIXEDSTRING },  // FixedString
    { "TagsFilter", 0x48, RF_ARRAY_GUID },  // Array<Guid>
};
static const ResourceField fields_PhotoModeSticker[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
    { "Asset", 0x28, RF_STDSTRING },  // STDString
};
static const ResourceField fields_PhotoModeVignette[] = {
    { "DisplayName", 0x18, RF_TRANSLATEDSTRING },  // TranslatedString
};

const ResourceLayout g_resource_layouts[] = {
    { "ActionResource", fields_ActionResource, 13, 0x5f },
    { "ClassDescription", fields_ClassDescription, 27, 0x110 },
    { "Tag", fields_Tag, 7, 0x64 },
    { "Faction", fields_Faction, 2, 0x30 },
    { "Race", fields_Race, 23, 0x168 },
    { "Origin", fields_Origin, 30, 0x1b0 },
    { "Background", fields_Background, 5, 0x71 },
    { "God", fields_God, 5, 0x60 },
    { "Progression", fields_Progression, 50, 0x350 },
    { "ProgressionDescription", fields_ProgressionDescription, 10, 0x70 },
    { "Gossip", fields_Gossip, 6, 0x58 },
    { "ActionResourceGroup", fields_ActionResourceGroup, 4, 0x60 },
    { "Color", fields_Color, 2, 0x3c },
    { "EquipmentType", fields_EquipmentType, 15, 0x54 },
    { "Flag", fields_Flag, 3, 0x39 },
    { "Feat", fields_Feat, 7, 0x148 },
    { "FeatDescription", fields_FeatDescription, 9, 0x60 },
    { "PassiveList", fields_PassiveList, 3, 0x40 },
    { "SkillList", fields_SkillList, 2, 0x40 },
    { "SpellList", fields_SpellList, 2, 0x60 },
    { "AbilityList", fields_AbilityList, 2, 0x40 },
    { "CompanionPreset", fields_CompanionPreset, 10, 0xb8 },
    { "AbilityDistributionPreset", fields_AbilityDistributionPreset, 8, 0x44 },
    { "CharacterCreationAccessorySet", fields_CharacterCreationAccessorySet, 6, 0x68 },
    { "CharacterCreationAppearanceMaterial", fields_CharacterCreationAppearanceMaterial, 11, 0xa8 },
    { "CharacterCreationAppearanceVisual", fields_CharacterCreationAppearanceVisual, 14, 0xa8 },
    { "CharacterCreationEquipmentIcons", fields_CharacterCreationEquipmentIcons, 6, 0x51 },
    { "CharacterCreationIconSettings", fields_CharacterCreationIconSettings, 3, 0x40 },
    { "CharacterCreationColor", fields_CharacterCreationColor, 4, 0x54 },
    { "CharacterCreationMaterialOverride", fields_CharacterCreationMaterialOverride, 5, 0x48 },
    { "CharacterCreationPassiveAppearance", fields_CharacterCreationPassiveAppearance, 5, 0x60 },
    { "CharacterCreationPreset", fields_CharacterCreationPreset, 9, 0xa8 },
    { "CharacterCreationSharedVisual", fields_CharacterCreationSharedVisual, 5, 0x58 },
    { "LevelMap", fields_LevelMap, 4, 0x30 },  // truncated at std::variant<int32_t, DiceRoll> FallbackValue
    { "ApprovalRating", fields_ApprovalRating, 3, 0x50 },
    { "AreaLevelOverride", fields_AreaLevelOverride, 3, 0x30 },
    { "AvatarContainerTemplates", fields_AvatarContainerTemplates, 1, 0x28 },
    { "BackgroundGoal", fields_BackgroundGoal, 6, 0x60 },
    { "CalendarDayRange", fields_CalendarDayRange, 7, 0x4c },
    { "CampChestTemplate", fields_CampChestTemplate, 1, 0x28 },
    { "DefaultValueGuidResource", fields_DefaultValueGuidResource, 7, 0x88 },
    { "CharacterCreationVOLine", fields_CharacterCreationVOLine, 2, 0x30 },
    { "CinematicArenaFrequencyGroup", fields_CinematicArenaFrequencyGroup, 3, 0x28 },
    { "CustomDiceTemplate", fields_CustomDiceTemplate, 9, 0x6d },
    { "ConditionErrorDescription", fields_ConditionErrorDescription, 4, 0x2e },
    { "DeathTypeEffect", fields_DeathTypeEffect, 3, 0x88 },
    { "DifficultyClass", fields_DifficultyClass, 3, 0x41 },
    { "DisturbanceProperty", fields_DisturbanceProperty, 1, 0x1c },
    { "DLC", fields_DLC, 8, 0x59 },
    { "EncumbranceType", fields_EncumbranceType, 1, 0x1c },
    { "EquipmentList", fields_EquipmentList, 3, 0x40 },
    { "ExperienceRewards", fields_ExperienceRewards, 4, 0x30 },
    { "FeatSoundState", fields_FeatSoundState, 5, 0x3c },
    { "FlagSoundState", fields_FlagSoundState, 5, 0x3c },
    { "GoldRewards", fields_GoldRewards, 4, 0x48 },
    { "FixedHotBarSlot", fields_FixedHotBarSlot, 4, 0x22 },
    { "ItemThrowParams", fields_ItemThrowParams, 6, 0x54 },
    { "ItemWallTemplate", fields_ItemWallTemplate, 11, 0xd0 },
    { "TrajectoryRule", fields_TrajectoryRule, 6, 0x30 },
    { "LimbsMapping", fields_LimbsMapping, 5, 0x68 },
    { "LongRestCost", fields_LongRestCost, 3, 0x24 },
    { "ManagedStatusVFX", fields_ManagedStatusVFX, 4, 0x28 },
    { "MultiEffectInfo", fields_MultiEffectInfo, 1, 0x40 },
    { "OriginIntroEntity", fields_OriginIntroEntity, 3, 0x30 },
    { "PassivesVFX", fields_PassivesVFX, 3, 0x24 },
    { "ProjectileDefault", fields_ProjectileDefault, 2, 0x30 },
    { "RandomCastOutcome", fields_RandomCastOutcome, 5, 0x3c },
    { "SoundSpellTrajectoryRule", fields_SoundSpellTrajectoryRule, 4, 0x28 },
    { "StatusSoundState", fields_StatusSoundState, 6, 0x2d },
    { "SurfaceCursorMessage", fields_SurfaceCursorMessage, 3, 0x30 },
    { "TadpolePower", fields_TadpolePower, 3, 0x2d },
    { "TagSoundState", fields_TagSoundState, 5, 0x3c },
    { "TooltipExtraText", fields_TooltipExtraText, 1, 0x28 },
    { "TooltipUpcastDescription", fields_TooltipUpcastDescription, 2, 0x2c },
    { "TutorialEntry", fields_TutorialEntry, 8, 0x7b },
    { "TutorialModalEntry", fields_TutorialModalEntry, 10, 0x58 },
    { "TutorialUnifiedEntry", fields_TutorialUnifiedEntry, 20, 0xc4 },
    { "TutorialEvent", fields_TutorialEvent, 5, 0x4d },
    { "VFX", fields_VFX, 2, 0x20 },
    { "Voice", fields_Voice, 5, 0x60 },
    { "WeaponAnimationSet", fields_WeaponAnimationSet, 3, 0x24 },
    { "WeightCategories", fields_WeightCategories, 3, 0x31 },
    { "ShapeshiftRule", fields_ShapeshiftRule, 51, 0x144 },
    { "AnimationSetPriority", fields_AnimationSetPriority, 3, 0x48 },
    { "SpellMetaCondition", fields_SpellMetaCondition, 4, 0x51 },
    { "ScriptMaterialParameterOverride", fields_ScriptMaterialParameterOverride, 4, 0x30 },  // truncated at std::variant<float, glm::vec3, glm::vec4, FixedString> Limit
    { "ScriptMaterialPresetOverride", fields_ScriptMaterialPresetOverride, 1, 0x28 },
    { "VisualLocatorAttachment", fields_VisualLocatorAttachment, 2, 0x20 },
    { "RulesetModifier", fields_RulesetModifier, 8, 0x78 },  // truncated at std::variant<NoValue, float, int, FixedString, bool> ParsedDefault
    { "RulesetModifierOption", fields_RulesetModifierOption, 5, 0x78 },  // truncated at std::variant<NoValue, float, int, FixedString, bool> ParsedValue
    { "Ruleset", fields_Ruleset, 6, 0x69 },
    { "RulesetValue", fields_RulesetValue, 3, 0x50 },  // truncated at std::variant<NoValue, float, int, FixedString, bool> Value
    { "RulesetSelectionPreset", fields_RulesetSelectionPreset, 6, 0x79 },
    { "OneTimeReward", fields_OneTimeReward, 2, 0x20 },
    { "AnimationShortNameCategory", fields_AnimationShortNameCategory, 1, 0x1c },
    { "AnimationShortName", fields_AnimationShortName, 2, 0x30 },
    { "PhotoModeBlueprintOverride", fields_PhotoModeBlueprintOverride, 2, 0x20 },
    { "PhotoModeColourGrading", fields_PhotoModeColourGrading, 2, 0x2c },
    { "PhotoModeDecorFrame", fields_PhotoModeDecorFrame, 7, 0x54 },
    { "PhotoModeEmoteAnimation", fields_PhotoModeEmoteAnimation, 4, 0x58 },
    { "PhotoModeEmoteCollection", fields_PhotoModeEmoteCollection, 4, 0x60 },
    { "PhotoModeEmotePose", fields_PhotoModeEmotePose, 5, 0x58 },
    { "PhotoModeFaceExpressionCollection", fields_PhotoModeFaceExpressionCollection, 3, 0x50 },
    { "PhotoModeFaceExpression", fields_PhotoModeFaceExpression, 4, 0x58 },
    { "PhotoModeSticker", fields_PhotoModeSticker, 2, 0x40 },
    { "PhotoModeVignette", fields_PhotoModeVignette, 1, 0x38 },
};

const int g_resource_layout_count = 106;
